#!/usr/bin/env node

import { Command } from 'commander';
import type { CurrentCapabilitySnapshot, ProofScenarioIndex } from '../../src/release/schemas.js';
import {
  formatMarkdown,
  loadJsonWithSchema,
  loadReleaseChecks,
  loadReleaseSchemas,
  loadYamlWithSchema,
  pathExists,
  writeOrCheck,
} from './shared.ts';

const OUT_REL = 'docs/release/readiness-report.generated.md';
const program = new Command('render-readiness-report').option('--check');
program.parse(process.argv.slice(2), { from: 'user' });
const check = program.opts<{ check?: boolean }>().check === true;

function bullet(items: readonly unknown[]): string {
  if (items.length === 0) return '- None';
  return items.map((item) => `- ${item}`).join('\n');
}

function table(headers: string[], rows: unknown[][]): string {
  const headerLine = `| ${headers.join(' | ')} |`;
  const sep = `| ${headers.map(() => '---').join(' | ')} |`;
  const body = rows.map((row) => `| ${row.map((cell) => String(cell ?? '')).join(' | ')} |`);
  return [headerLine, sep, ...body].join('\n');
}

function proofVerified(proofs: ProofScenarioIndex, id: string): boolean {
  return proofs.scenarios.some(
    (scenario) => scenario.id === id && scenario.status === 'verified_current',
  );
}

function capabilityStatus(current: CurrentCapabilitySnapshot, id: string): string | undefined {
  return current.capabilities.find((capability) => capability.id === id)?.status;
}

async function main() {
  const schemas = await loadReleaseSchemas();
  const checks = await loadReleaseChecks();
  const original = loadYamlWithSchema(
    'docs/release/parity/original-circuit.yaml',
    schemas.OriginalCapabilitySnapshot,
  );
  const current = loadJsonWithSchema(
    'generated/release/current-capabilities.json',
    schemas.CurrentCapabilitySnapshot,
  );
  const exceptions = loadYamlWithSchema(
    'docs/release/parity/exceptions.yaml',
    schemas.ParityExceptionLedger,
  );
  const claims = loadYamlWithSchema(
    'docs/release/claims/public-claims.yaml',
    schemas.PublicClaimLedger,
  );
  const proofs = loadYamlWithSchema('docs/release/proofs/index.yaml', schemas.ProofScenarioIndex);

  const parity = checks.compareParity({ original, current, exceptions });
  const claimCheck = checks.validatePublicClaims({
    claims,
    current,
    proofs,
    exceptions,
    pathExists,
  });
  const proofCheck = checks.validateProofCoverage({ proofs, exceptions, pathExists });
  const blockers = checks.releaseBlockers({ exceptions, claims, proofs });
  const warnings = [...parity.warnings, ...claimCheck.warnings, ...proofCheck.warnings];
  const issues = [...parity.issues, ...claimCheck.issues, ...proofCheck.issues];

  const statusRows = [
    ['Original capabilities', original.capabilities.length],
    ['Current capabilities', current.capabilities.length],
    ['Tracked exceptions', exceptions.exceptions.length],
    ['Public claims', claims.claims.length],
    ['Proof scenarios', proofs.scenarios.length],
    ['Release blockers', blockers.length],
    ['Infra issues', issues.length],
  ];
  const nextActions =
    blockers.length === 0
      ? [
          'Decide whether the approved Fix Lite intent exception needs public release-note wording.',
          'Harden the partial host surfaces that are outside original parity: generic shell text progress and current plugin host wording.',
          'Keep golden runs refreshed whenever command, summary, or report contracts change.',
          'Run `npm run check-release-ready` as the strict final release check.',
        ]
      : [
          proofVerified(proofs, 'proof:explore-decision')
            ? 'Use the verified Explore Tournament proof to keep shrinking Explore behavioral axes.'
            : 'Capture the golden Explore Tournament proof for proof:explore-decision.',
          capabilityStatus(current, 'route-outcomes:rich') === 'implemented'
            ? 'Use the executable rich route substrate in checkpoint, recovery, and failure proof runs.'
            : 'Implement or fail generation for rich route outcomes.',
          'Finish the custom connector guide with a copy-pasteable file-protocol example.',
          'Capture golden release runs across proof categories.',
          'Replace hand-maintained support claims with generated matrix blocks.',
        ];

  const lines = [
    '# Circuit Release Readiness Report',
    '',
    '<!-- Generated by scripts/release/render-readiness-report.ts. Do not edit by hand. -->',
    '',
    'Infra checks may pass while release blockers remain. `npm run check-release-ready` is the strict gate.',
    '',
    '## Summary',
    '',
    table(['Measure', 'Value'], statusRows),
    '',
    '## Infra Issues',
    '',
    bullet(issues),
    '',
    '## Tracked Warnings',
    '',
    bullet(warnings),
    '',
    '## Release Blockers',
    '',
    bullet(blockers),
    '',
    '## Next Actions',
    '',
    bullet(nextActions),
    '',
    '## Source Files',
    '',
    bullet([
      'docs/release/parity/original-circuit.yaml',
      'generated/release/current-capabilities.json',
      'docs/release/parity/exceptions.yaml',
      'docs/release/claims/public-claims.yaml',
      'docs/release/proofs/index.yaml',
      'docs/release/parity-matrix.generated.md',
    ]),
    '',
  ];

  writeOrCheck(OUT_REL, formatMarkdown(lines.join('\n')), check);
}

main().catch((err) => {
  console.error(err instanceof Error ? err.message : String(err));
  process.exit(1);
});
