export type PublicRuntimePathCategory =
  | 'connector-wrapper'
  | 'flow-authoring-wrapper'
  | 'public-runner-surface'
  | 'registry-wrapper'
  | 'retained-handler'
  | 'retained-implementation'
  | 'retained-saved-state'
  | 'run-status-wrapper'
  | 'shared-helper-wrapper';

export type PublicRuntimePathDisposition =
  | 'future-deprecation-candidate'
  | 'keep'
  | 'retained-owned';

export type PublicRuntimePathDeprecationStage = 'none' | 'soft-deprecated';

export interface PublicRuntimePathEntry {
  readonly oldPath: string;
  readonly category: PublicRuntimePathCategory;
  readonly currentDisposition: PublicRuntimePathDisposition;
  readonly deprecationStage: PublicRuntimePathDeprecationStage;
  readonly requiresReviewBeforeDeletion: true;
  readonly currentOwnerPath?: string;
  readonly compatibilityTestPaths: readonly string[];
  readonly notes: string;
}

export const PUBLIC_RUNTIME_PATHS: readonly PublicRuntimePathEntry[] = [
  {
    oldPath: 'src/runtime/catalog-derivations.ts',
    currentOwnerPath: 'src/flows/catalog-derivations.ts',
    category: 'registry-wrapper',
    currentDisposition: 'keep',
    deprecationStage: 'none',
    requiresReviewBeforeDeletion: true,
    compatibilityTestPaths: ['tests/runner/catalog-derivations.test.ts'],
    notes: 'Old catalog derivation import path.',
  },
  {
    oldPath: 'src/runtime/checkpoint-resume.ts',
    category: 'retained-saved-state',
    currentDisposition: 'retained-owned',
    deprecationStage: 'none',
    requiresReviewBeforeDeletion: true,
    compatibilityTestPaths: ['tests/runner/retained-compat-facade.test.ts'],
    notes: 'Retired v1 checkpoint resume path; direct preparation fails closed.',
  },
  {
    oldPath: 'src/runtime/compile-schematic-to-flow.ts',
    currentOwnerPath: 'src/flows/compile-schematic-to-flow.ts',
    category: 'flow-authoring-wrapper',
    currentDisposition: 'future-deprecation-candidate',
    deprecationStage: 'soft-deprecated',
    requiresReviewBeforeDeletion: true,
    compatibilityTestPaths: ['tests/runner/retained-compat-facade.test.ts'],
    notes: 'Old schematic compiler import path.',
  },
  {
    oldPath: 'src/runtime/config-loader.ts',
    currentOwnerPath: 'src/shared/config-loader.ts',
    category: 'shared-helper-wrapper',
    currentDisposition: 'future-deprecation-candidate',
    deprecationStage: 'soft-deprecated',
    requiresReviewBeforeDeletion: true,
    compatibilityTestPaths: ['tests/runner/shared-helper-compat.test.ts'],
    notes: 'Old config loading helper path.',
  },
  {
    oldPath: 'src/runtime/connectors/claude-code.ts',
    currentOwnerPath: 'src/connectors/claude-code.ts',
    category: 'connector-wrapper',
    currentDisposition: 'keep',
    deprecationStage: 'none',
    requiresReviewBeforeDeletion: true,
    compatibilityTestPaths: ['tests/runner/connector-shared-compat.test.ts'],
    notes: 'Old Claude Code connector import path.',
  },
  {
    oldPath: 'src/runtime/connectors/codex.ts',
    currentOwnerPath: 'src/connectors/codex.ts',
    category: 'connector-wrapper',
    currentDisposition: 'keep',
    deprecationStage: 'none',
    requiresReviewBeforeDeletion: true,
    compatibilityTestPaths: ['tests/runner/connector-shared-compat.test.ts'],
    notes: 'Old Codex connector import path.',
  },
  {
    oldPath: 'src/runtime/connectors/custom.ts',
    currentOwnerPath: 'src/connectors/custom.ts',
    category: 'connector-wrapper',
    currentDisposition: 'keep',
    deprecationStage: 'none',
    requiresReviewBeforeDeletion: true,
    compatibilityTestPaths: ['tests/runner/connector-shared-compat.test.ts'],
    notes: 'Old custom connector import path.',
  },
  {
    oldPath: 'src/runtime/connectors/relay-materializer.ts',
    currentOwnerPath: 'src/connectors/relay-materializer.ts',
    category: 'connector-wrapper',
    currentDisposition: 'keep',
    deprecationStage: 'none',
    requiresReviewBeforeDeletion: true,
    compatibilityTestPaths: ['tests/runner/connector-shared-compat.test.ts'],
    notes: 'Old relay materializer import path.',
  },
  {
    oldPath: 'src/runtime/connectors/shared.ts',
    currentOwnerPath: 'src/connectors/shared.ts',
    category: 'connector-wrapper',
    currentDisposition: 'keep',
    deprecationStage: 'none',
    requiresReviewBeforeDeletion: true,
    compatibilityTestPaths: ['tests/runner/connector-shared-compat.test.ts'],
    notes: 'Old connector shared helper import path.',
  },
  {
    oldPath: 'src/runtime/manifest-snapshot-writer.ts',
    currentOwnerPath: 'src/shared/manifest-snapshot.ts',
    category: 'shared-helper-wrapper',
    currentDisposition: 'future-deprecation-candidate',
    deprecationStage: 'soft-deprecated',
    requiresReviewBeforeDeletion: true,
    compatibilityTestPaths: [
      'tests/runner/shared-helper-compat.test.ts',
      'tests/unit/runtime/event-log-round-trip.test.ts',
    ],
    notes: 'Old manifest snapshot helper path.',
  },
  {
    oldPath: 'src/runtime/operator-summary-writer.ts',
    currentOwnerPath: 'src/shared/operator-summary-writer.ts',
    category: 'shared-helper-wrapper',
    currentDisposition: 'future-deprecation-candidate',
    deprecationStage: 'soft-deprecated',
    requiresReviewBeforeDeletion: true,
    compatibilityTestPaths: [
      'tests/runner/shared-helper-compat.test.ts',
      'tests/runner/operator-summary-writer.test.ts',
    ],
    notes: 'Old operator summary writer path.',
  },
  {
    oldPath: 'src/runtime/policy/flow-kind-policy.ts',
    currentOwnerPath: 'src/shared/flow-kind-policy.ts',
    category: 'shared-helper-wrapper',
    currentDisposition: 'future-deprecation-candidate',
    deprecationStage: 'soft-deprecated',
    requiresReviewBeforeDeletion: true,
    compatibilityTestPaths: ['tests/runner/shared-helper-compat.test.ts'],
    notes: 'Old flow-kind policy helper path.',
  },
  {
    oldPath: 'src/runtime/progress-projector.ts',
    category: 'retained-saved-state',
    currentDisposition: 'retained-owned',
    deprecationStage: 'none',
    requiresReviewBeforeDeletion: true,
    compatibilityTestPaths: ['tests/unit/runtime/progress-projector.test.ts'],
    notes: 'Retained v1 trace-to-progress projection.',
  },
  {
    oldPath: 'src/runtime/reducer.ts',
    category: 'retained-saved-state',
    currentDisposition: 'retained-owned',
    deprecationStage: 'none',
    requiresReviewBeforeDeletion: true,
    compatibilityTestPaths: ['tests/unit/runtime/event-log-round-trip.test.ts'],
    notes: 'Retained v1 trace reducer.',
  },
  {
    oldPath: 'src/runtime/registries/checkpoint-writers/registry.ts',
    currentOwnerPath: 'src/flows/registries/checkpoint-writers/registry.ts',
    category: 'registry-wrapper',
    currentDisposition: 'keep',
    deprecationStage: 'none',
    requiresReviewBeforeDeletion: true,
    compatibilityTestPaths: ['tests/runner/catalog-derivations.test.ts'],
    notes: 'Old checkpoint writer registry path.',
  },
  {
    oldPath: 'src/runtime/registries/checkpoint-writers/types.ts',
    currentOwnerPath: 'src/flows/registries/checkpoint-writers/types.ts',
    category: 'registry-wrapper',
    currentDisposition: 'keep',
    deprecationStage: 'none',
    requiresReviewBeforeDeletion: true,
    compatibilityTestPaths: ['tests/runner/public-runtime-paths.test.ts'],
    notes: 'Old checkpoint writer registry type path.',
  },
  {
    oldPath: 'src/runtime/registries/close-writers/registry.ts',
    currentOwnerPath: 'src/flows/registries/close-writers/registry.ts',
    category: 'registry-wrapper',
    currentDisposition: 'keep',
    deprecationStage: 'none',
    requiresReviewBeforeDeletion: true,
    compatibilityTestPaths: ['tests/runner/catalog-derivations.test.ts'],
    notes: 'Old close writer registry path.',
  },
  {
    oldPath: 'src/runtime/registries/close-writers/shared.ts',
    currentOwnerPath: 'src/flows/registries/close-writers/shared.ts',
    category: 'registry-wrapper',
    currentDisposition: 'keep',
    deprecationStage: 'none',
    requiresReviewBeforeDeletion: true,
    compatibilityTestPaths: ['tests/runner/public-runtime-paths.test.ts'],
    notes: 'Old close writer registry shared helper path.',
  },
  {
    oldPath: 'src/runtime/registries/close-writers/types.ts',
    currentOwnerPath: 'src/flows/registries/close-writers/types.ts',
    category: 'registry-wrapper',
    currentDisposition: 'keep',
    deprecationStage: 'none',
    requiresReviewBeforeDeletion: true,
    compatibilityTestPaths: ['tests/runner/public-runtime-paths.test.ts'],
    notes: 'Old close writer registry type path.',
  },
  {
    oldPath: 'src/runtime/registries/compose-writers/registry.ts',
    currentOwnerPath: 'src/flows/registries/compose-writers/registry.ts',
    category: 'registry-wrapper',
    currentDisposition: 'keep',
    deprecationStage: 'none',
    requiresReviewBeforeDeletion: true,
    compatibilityTestPaths: ['tests/runner/catalog-derivations.test.ts'],
    notes: 'Old compose writer registry path.',
  },
  {
    oldPath: 'src/runtime/registries/compose-writers/types.ts',
    currentOwnerPath: 'src/flows/registries/compose-writers/types.ts',
    category: 'registry-wrapper',
    currentDisposition: 'keep',
    deprecationStage: 'none',
    requiresReviewBeforeDeletion: true,
    compatibilityTestPaths: ['tests/runner/public-runtime-paths.test.ts'],
    notes: 'Old compose writer registry type path.',
  },
  {
    oldPath: 'src/runtime/registries/cross-report-validators.ts',
    currentOwnerPath: 'src/flows/registries/cross-report-validators.ts',
    category: 'registry-wrapper',
    currentDisposition: 'keep',
    deprecationStage: 'none',
    requiresReviewBeforeDeletion: true,
    compatibilityTestPaths: ['tests/runner/catalog-derivations.test.ts'],
    notes: 'Old cross-report validator registry path.',
  },
  {
    oldPath: 'src/runtime/registries/report-schemas.ts',
    currentOwnerPath: 'src/flows/registries/report-schemas.ts',
    category: 'registry-wrapper',
    currentDisposition: 'keep',
    deprecationStage: 'none',
    requiresReviewBeforeDeletion: true,
    compatibilityTestPaths: ['tests/runner/catalog-derivations.test.ts'],
    notes: 'Old report schema registry path.',
  },
  {
    oldPath: 'src/runtime/registries/shape-hints/registry.ts',
    currentOwnerPath: 'src/flows/registries/shape-hints/registry.ts',
    category: 'registry-wrapper',
    currentDisposition: 'keep',
    deprecationStage: 'none',
    requiresReviewBeforeDeletion: true,
    compatibilityTestPaths: ['tests/runner/catalog-derivations.test.ts'],
    notes: 'Old relay shape-hint registry path.',
  },
  {
    oldPath: 'src/runtime/registries/shape-hints/types.ts',
    currentOwnerPath: 'src/flows/registries/shape-hints/types.ts',
    category: 'registry-wrapper',
    currentDisposition: 'keep',
    deprecationStage: 'none',
    requiresReviewBeforeDeletion: true,
    compatibilityTestPaths: ['tests/runner/public-runtime-paths.test.ts'],
    notes: 'Old relay shape-hint registry type path.',
  },
  {
    oldPath: 'src/runtime/registries/verification-writers/registry.ts',
    currentOwnerPath: 'src/flows/registries/verification-writers/registry.ts',
    category: 'registry-wrapper',
    currentDisposition: 'keep',
    deprecationStage: 'none',
    requiresReviewBeforeDeletion: true,
    compatibilityTestPaths: ['tests/runner/catalog-derivations.test.ts'],
    notes: 'Old verification writer registry path.',
  },
  {
    oldPath: 'src/runtime/registries/verification-writers/types.ts',
    currentOwnerPath: 'src/flows/registries/verification-writers/types.ts',
    category: 'registry-wrapper',
    currentDisposition: 'keep',
    deprecationStage: 'none',
    requiresReviewBeforeDeletion: true,
    compatibilityTestPaths: ['tests/runner/public-runtime-paths.test.ts'],
    notes: 'Old verification writer registry type path.',
  },
  {
    oldPath: 'src/runtime/relay-selection.ts',
    category: 'retained-implementation',
    currentDisposition: 'retained-owned',
    deprecationStage: 'none',
    requiresReviewBeforeDeletion: true,
    compatibilityTestPaths: ['tests/runner/runner-relay-provenance.test.ts'],
    notes: 'Retained relay decision bridge and provenance behavior.',
  },
  {
    oldPath: 'src/runtime/relay-support.ts',
    currentOwnerPath: 'src/shared/relay-support.ts',
    category: 'shared-helper-wrapper',
    currentDisposition: 'future-deprecation-candidate',
    deprecationStage: 'soft-deprecated',
    requiresReviewBeforeDeletion: true,
    compatibilityTestPaths: ['tests/runner/shared-helper-compat.test.ts'],
    notes: 'Old relay prompt/check helper path.',
  },
  {
    oldPath: 'src/runtime/result-writer.ts',
    category: 'retained-implementation',
    currentDisposition: 'retained-owned',
    deprecationStage: 'none',
    requiresReviewBeforeDeletion: true,
    compatibilityTestPaths: ['tests/runner/result-path-compat.test.ts'],
    notes: 'Retained result writer and old result-path compatibility surface.',
  },
  {
    oldPath: 'src/runtime/router.ts',
    currentOwnerPath: 'src/flows/router.ts',
    category: 'flow-authoring-wrapper',
    currentDisposition: 'future-deprecation-candidate',
    deprecationStage: 'soft-deprecated',
    requiresReviewBeforeDeletion: true,
    compatibilityTestPaths: ['tests/runner/retained-compat-facade.test.ts'],
    notes: 'Old router import path.',
  },
  {
    oldPath: 'src/runtime/run-relative-path.ts',
    currentOwnerPath: 'src/shared/run-relative-path.ts',
    category: 'shared-helper-wrapper',
    currentDisposition: 'future-deprecation-candidate',
    deprecationStage: 'soft-deprecated',
    requiresReviewBeforeDeletion: true,
    compatibilityTestPaths: ['tests/runner/shared-helper-compat.test.ts'],
    notes: 'Old run-relative path helper.',
  },
  {
    oldPath: 'src/runtime/run-status-projection.ts',
    currentOwnerPath: 'src/run-status/project-run-folder.ts',
    category: 'run-status-wrapper',
    currentDisposition: 'keep',
    deprecationStage: 'none',
    requiresReviewBeforeDeletion: true,
    compatibilityTestPaths: ['tests/runner/run-status-facade.test.ts'],
    notes: 'Old run-status public facade path.',
  },
  {
    oldPath: 'src/runtime/runner-types.ts',
    category: 'public-runner-surface',
    currentDisposition: 'retained-owned',
    deprecationStage: 'none',
    requiresReviewBeforeDeletion: true,
    compatibilityTestPaths: ['tests/runner/public-runtime-paths.test.ts'],
    notes: 'Retained invocation/result types and old runner type surface.',
  },
  {
    oldPath: 'src/runtime/runner.ts',
    category: 'public-runner-surface',
    currentDisposition: 'retained-owned',
    deprecationStage: 'none',
    requiresReviewBeforeDeletion: true,
    compatibilityTestPaths: ['tests/runner/retained-compat-facade.test.ts'],
    notes: 'Retained execution fallback plus old public writeComposeReport path.',
  },
  {
    oldPath: 'src/runtime/selection-resolver.ts',
    currentOwnerPath: 'src/shared/selection-resolver.ts',
    category: 'shared-helper-wrapper',
    currentDisposition: 'future-deprecation-candidate',
    deprecationStage: 'soft-deprecated',
    requiresReviewBeforeDeletion: true,
    compatibilityTestPaths: ['tests/runner/shared-helper-compat.test.ts'],
    notes: 'Old selection resolver helper path.',
  },
  {
    oldPath: 'src/runtime/snapshot-writer.ts',
    category: 'retained-saved-state',
    currentDisposition: 'retained-owned',
    deprecationStage: 'none',
    requiresReviewBeforeDeletion: true,
    compatibilityTestPaths: ['tests/unit/runtime/event-log-round-trip.test.ts'],
    notes: 'Retained state snapshot derivation from v1 traces.',
  },
  {
    oldPath: 'src/runtime/step-handlers/checkpoint.ts',
    category: 'retained-handler',
    currentDisposition: 'retained-owned',
    deprecationStage: 'none',
    requiresReviewBeforeDeletion: true,
    compatibilityTestPaths: ['tests/runner/retained-compat-facade.test.ts'],
    notes: 'Retired checkpoint handler path; direct execution fails closed.',
  },
  {
    oldPath: 'src/runtime/step-handlers/fanout/aggregate.ts',
    currentOwnerPath: 'src/shared/fanout-aggregate-report.ts',
    category: 'shared-helper-wrapper',
    currentDisposition: 'future-deprecation-candidate',
    deprecationStage: 'soft-deprecated',
    requiresReviewBeforeDeletion: true,
    compatibilityTestPaths: ['tests/runner/fanout-aggregate-compat.test.ts'],
    notes: 'Old fanout aggregate helper path.',
  },
  {
    oldPath: 'src/runtime/step-handlers/fanout/join-policy.ts',
    currentOwnerPath: 'src/shared/fanout-join-policy.ts',
    category: 'shared-helper-wrapper',
    currentDisposition: 'future-deprecation-candidate',
    deprecationStage: 'soft-deprecated',
    requiresReviewBeforeDeletion: true,
    compatibilityTestPaths: ['tests/properties/visible/fanout-join-policy.test.ts'],
    notes: 'Old fanout join-policy helper path.',
  },
  {
    oldPath: 'src/runtime/step-handlers/recovery-route.ts',
    currentOwnerPath: 'src/shared/recovery-route.ts',
    category: 'shared-helper-wrapper',
    currentDisposition: 'future-deprecation-candidate',
    deprecationStage: 'soft-deprecated',
    requiresReviewBeforeDeletion: true,
    compatibilityTestPaths: ['tests/runner/recovery-route-compat.test.ts'],
    notes: 'Old recovery route priority helper path.',
  },
  {
    oldPath: 'src/runtime/step-handlers/shared.ts',
    currentOwnerPath: 'src/shared/json-report.ts',
    category: 'shared-helper-wrapper',
    currentDisposition: 'future-deprecation-candidate',
    deprecationStage: 'soft-deprecated',
    requiresReviewBeforeDeletion: true,
    compatibilityTestPaths: ['tests/runner/json-report-compat.test.ts'],
    notes: 'Old retained handler JSON report helper path.',
  },
  {
    oldPath: 'src/runtime/terminal-verdict.ts',
    currentOwnerPath: 'src/shared/terminal-verdict.ts',
    category: 'shared-helper-wrapper',
    currentDisposition: 'future-deprecation-candidate',
    deprecationStage: 'soft-deprecated',
    requiresReviewBeforeDeletion: true,
    compatibilityTestPaths: ['tests/runner/terminal-verdict-helper.test.ts'],
    notes: 'Old terminal verdict helper path.',
  },
  {
    oldPath: 'src/runtime/trace-reader.ts',
    category: 'retained-saved-state',
    currentDisposition: 'retained-owned',
    deprecationStage: 'none',
    requiresReviewBeforeDeletion: true,
    compatibilityTestPaths: ['tests/unit/runtime/event-log-round-trip.test.ts'],
    notes: 'Retained v1 trace reader.',
  },
  {
    oldPath: 'src/runtime/trace-writer.ts',
    category: 'retained-saved-state',
    currentDisposition: 'retained-owned',
    deprecationStage: 'none',
    requiresReviewBeforeDeletion: true,
    compatibilityTestPaths: ['tests/unit/runtime/event-log-round-trip.test.ts'],
    notes: 'Retained v1 trace writer.',
  },
  {
    oldPath: 'src/runtime/append-and-derive.ts',
    category: 'retained-saved-state',
    currentDisposition: 'retained-owned',
    deprecationStage: 'none',
    requiresReviewBeforeDeletion: true,
    compatibilityTestPaths: ['tests/runner/public-runtime-paths.test.ts'],
    notes: 'Retained v1 trace append and snapshot derivation helper.',
  },
  {
    oldPath: 'src/runtime/write-capable-worker-disclosure.ts',
    currentOwnerPath: 'src/shared/write-capable-worker-disclosure.ts',
    category: 'shared-helper-wrapper',
    currentDisposition: 'future-deprecation-candidate',
    deprecationStage: 'soft-deprecated',
    requiresReviewBeforeDeletion: true,
    compatibilityTestPaths: ['tests/runner/shared-helper-compat.test.ts'],
    notes: 'Old write-capable disclosure helper path.',
  },
];

export const PUBLIC_RUNTIME_WRAPPER_PATHS = PUBLIC_RUNTIME_PATHS.filter(
  (entry) => entry.currentOwnerPath !== undefined,
);

export const PUBLIC_RUNTIME_RETAINED_PATHS = PUBLIC_RUNTIME_PATHS.filter(
  (entry) => entry.currentOwnerPath === undefined,
);

export const PUBLIC_RUNTIME_SOFT_DEPRECATED_PATHS = PUBLIC_RUNTIME_PATHS.filter(
  (entry) => entry.deprecationStage === 'soft-deprecated',
);
