import type { FlowFact } from '../flow-definition.js';

export const pursueFacts = [
  {
    kind: 'flow',
    flowId: 'pursue',
    title: 'Pursue Schematic',
    purpose:
      'Pursue flow: turn one or more rough operator ideas into pursuit contracts, coordinate their order, execute code-changing work serially, verify, review for interference, and close with evidence.',
    status: 'active',
    version: '0.1.0',
    visibility: 'public',
    startsAt: 'contract-step',
    stagePathPolicy: {
      mode: 'partial',
      omits: ['analyze'],
      rationale:
        'Pursuits V1 folds read-only discovery policy into the coordination graph before acting; a separate Analyze stage can be added when dynamic discovery fanout lands.',
    },
  },
  {
    kind: 'path',
    flowId: 'pursue',
    pathKind: 'schematic',
    path: 'src/flows/pursue/schematic.json',
  },
  {
    kind: 'entry',
    flowId: 'pursue',
    include: ['pursue', 'pursuit', 'coordinate pursuits', 'multiple autonomous goals'],
    exclude: [],
    intentPrefixes: ['pursue'],
  },
  {
    kind: 'mode',
    flowId: 'pursue',
    name: 'default',
    depth: 'standard',
    description: 'Default Pursue entry mode.',
  },
  {
    kind: 'mode',
    flowId: 'pursue',
    name: 'autonomous',
    depth: 'autonomous',
    description: 'Autonomous Pursue entry mode with the same serial-write safety policy.',
  },
  {
    kind: 'initial-contract',
    flowId: 'pursue',
    schemaName: 'task.intake@v1',
  },
  {
    kind: 'initial-contract',
    flowId: 'pursue',
    schemaName: 'route.decision@v1',
  },
  {
    kind: 'initial-contract',
    flowId: 'pursue',
    schemaName: 'verification.plan@v1',
  },
  {
    kind: 'contract-alias',
    flowId: 'pursue',
    generic: 'flow.brief@v1',
    actual: 'pursuit.contract@v1',
  },
  {
    kind: 'contract-alias',
    flowId: 'pursue',
    generic: 'plan.strategy@v1',
    actual: 'pursuit.wave-plan@v1',
  },
  {
    kind: 'contract-alias',
    flowId: 'pursue',
    generic: 'work.queue@v1',
    actual: 'pursuit.graph@v1',
  },
  {
    kind: 'contract-alias',
    flowId: 'pursue',
    generic: 'batch.result@v1',
    actual: 'pursuit.batch@v1',
  },
  {
    kind: 'contract-alias',
    flowId: 'pursue',
    generic: 'change.evidence@v1',
    actual: 'pursuit.batch@v1',
  },
  {
    kind: 'contract-alias',
    flowId: 'pursue',
    generic: 'verification.result@v1',
    actual: 'pursuit.verification@v1',
  },
  {
    kind: 'contract-alias',
    flowId: 'pursue',
    generic: 'review.verdict@v1',
    actual: 'pursuit.review@v1',
  },
  {
    kind: 'contract-alias',
    flowId: 'pursue',
    generic: 'flow.result@v1',
    actual: 'pursuit.result@v1',
  },
  {
    kind: 'stage',
    flowId: 'pursue',
    stageId: 'frame-stage',
    canonical: 'frame',
    title: 'Frame',
  },
  {
    kind: 'stage',
    flowId: 'pursue',
    stageId: 'plan-stage',
    canonical: 'plan',
    title: 'Coordinate',
  },
  {
    kind: 'stage',
    flowId: 'pursue',
    stageId: 'act-stage',
    canonical: 'act',
    title: 'Execute',
  },
  {
    kind: 'stage',
    flowId: 'pursue',
    stageId: 'verify-stage',
    canonical: 'verify',
    title: 'Verify',
  },
  {
    kind: 'stage',
    flowId: 'pursue',
    stageId: 'review-stage',
    canonical: 'review',
    title: 'Review',
  },
  {
    kind: 'stage',
    flowId: 'pursue',
    stageId: 'close-stage',
    canonical: 'close',
    title: 'Close',
  },
  {
    kind: 'input-key',
    flowId: 'pursue',
    stepId: 'contract-step',
    key: 'intake',
    schemaName: 'task.intake@v1',
  },
  {
    kind: 'input-key',
    flowId: 'pursue',
    stepId: 'contract-step',
    key: 'route',
    schemaName: 'route.decision@v1',
  },
  {
    kind: 'step',
    flowId: 'pursue',
    stepId: 'contract-step',
    title: 'Frame - create pursuit contract',
    stage: 'frame',
    block: 'pursue',
    output: 'pursuit.contract@v1',
    evidenceRequirements: [
      'ownership contract',
      'estimated touch set',
      'proof plan',
      'check-in triggers',
    ],
    execution: {
      kind: 'compose',
    },
    protocol: 'pursuit-contract@v1',
    writes: {
      report_path: 'reports/pursuit/contract.json',
    },
    check: {
      required: ['objective', 'pursuits', 'verification_command_candidates'],
    },
    skillSlots: [],
  },
  {
    kind: 'route',
    flowId: 'pursue',
    fromStepId: 'contract-step',
    outcome: 'continue',
    to: 'graph-step',
  },
  {
    kind: 'route',
    flowId: 'pursue',
    fromStepId: 'contract-step',
    outcome: 'stop',
    to: '@stop',
  },
  {
    kind: 'input-key',
    flowId: 'pursue',
    stepId: 'graph-step',
    key: 'contract',
    schemaName: 'pursuit.contract@v1',
  },
  {
    kind: 'step',
    flowId: 'pursue',
    stepId: 'graph-step',
    title: 'Coordinate - build pursuit graph',
    stage: 'plan',
    block: 'coordinate-pursuits',
    output: 'pursuit.graph@v1',
    evidenceRequirements: [
      'dependency graph',
      'conflict analysis',
      'serial groups',
      'parallel read-only groups',
    ],
    execution: {
      kind: 'compose',
    },
    protocol: 'pursuit-graph@v1',
    writes: {
      report_path: 'reports/pursuit/graph.json',
    },
    check: {
      required: ['nodes', 'serial_groups', 'parallel_read_only_groups'],
    },
    skillSlots: [],
  },
  {
    kind: 'route',
    flowId: 'pursue',
    fromStepId: 'graph-step',
    outcome: 'continue',
    to: 'wave-plan-step',
  },
  {
    kind: 'route',
    flowId: 'pursue',
    fromStepId: 'graph-step',
    outcome: 'stop',
    to: '@stop',
  },
  {
    kind: 'input-key',
    flowId: 'pursue',
    stepId: 'wave-plan-step',
    key: 'brief',
    schemaName: 'pursuit.contract@v1',
  },
  {
    kind: 'input-key',
    flowId: 'pursue',
    stepId: 'wave-plan-step',
    key: 'context',
    schemaName: 'pursuit.graph@v1',
  },
  {
    kind: 'step',
    flowId: 'pursue',
    stepId: 'wave-plan-step',
    title: 'Plan - order execution waves',
    stage: 'plan',
    block: 'plan',
    output: 'pursuit.wave-plan@v1',
    evidenceRequirements: ['ordered steps', 'risk notes', 'proof strategy'],
    execution: {
      kind: 'compose',
    },
    protocol: 'pursuit-wave-plan@v1',
    writes: {
      report_path: 'reports/pursuit/wave-plan.json',
    },
    check: {
      required: ['waves', 'no_parallel_writes_reason'],
    },
    skillSlots: [],
  },
  {
    kind: 'route',
    flowId: 'pursue',
    fromStepId: 'wave-plan-step',
    outcome: 'continue',
    to: 'batch-step',
  },
  {
    kind: 'route',
    flowId: 'pursue',
    fromStepId: 'wave-plan-step',
    outcome: 'stop',
    to: '@stop',
  },
  {
    kind: 'input-key',
    flowId: 'pursue',
    stepId: 'batch-step',
    key: 'queue',
    schemaName: 'pursuit.graph@v1',
  },
  {
    kind: 'input-key',
    flowId: 'pursue',
    stepId: 'batch-step',
    key: 'brief',
    schemaName: 'pursuit.contract@v1',
  },
  {
    kind: 'input-key',
    flowId: 'pursue',
    stepId: 'batch-step',
    key: 'plan',
    schemaName: 'pursuit.wave-plan@v1',
  },
  {
    kind: 'step',
    flowId: 'pursue',
    stepId: 'batch-step',
    title: 'Execute - run serialized pursuit batch',
    stage: 'act',
    block: 'batch',
    output: 'pursuit.batch@v1',
    evidenceRequirements: ['completed items', 'skipped items', 'blocked items', 'failed items'],
    execution: {
      kind: 'relay',
      role: 'implementer',
    },
    protocol: 'pursuit-batch@v1',
    writes: {
      report_path: 'reports/pursuit/batch.json',
      request_path: 'reports/relay/pursuit-batch.request.json',
      receipt_path: 'reports/relay/pursuit-batch.receipt.txt',
      result_path: 'reports/relay/pursuit-batch.result.json',
    },
    check: {
      pass: ['accept', 'partial'],
    },
    skillSlots: [],
  },
  {
    kind: 'route',
    flowId: 'pursue',
    fromStepId: 'batch-step',
    outcome: 'continue',
    to: 'verify-step',
  },
  {
    kind: 'route',
    flowId: 'pursue',
    fromStepId: 'batch-step',
    outcome: 'retry',
    to: 'batch-step',
  },
  {
    kind: 'route',
    flowId: 'pursue',
    fromStepId: 'batch-step',
    outcome: 'stop',
    to: '@stop',
  },
  {
    kind: 'input-key',
    flowId: 'pursue',
    stepId: 'verify-step',
    key: 'proof',
    schemaName: 'verification.plan@v1',
  },
  {
    kind: 'input-key',
    flowId: 'pursue',
    stepId: 'verify-step',
    key: 'brief',
    schemaName: 'pursuit.contract@v1',
  },
  {
    kind: 'input-key',
    flowId: 'pursue',
    stepId: 'verify-step',
    key: 'change',
    schemaName: 'pursuit.batch@v1',
  },
  {
    kind: 'step',
    flowId: 'pursue',
    stepId: 'verify-step',
    title: 'Verify - run Pursue proof commands',
    stage: 'verify',
    block: 'run-verification',
    output: 'pursuit.verification@v1',
    evidenceRequirements: ['command list', 'exit status', 'bounded output', 'pass or fail'],
    execution: {
      kind: 'verification',
    },
    protocol: 'pursuit-verify@v1',
    writes: {
      report_path: 'reports/pursuit/verification.json',
    },
    check: {
      required: ['overall_status', 'commands'],
    },
    skillSlots: [],
  },
  {
    kind: 'route',
    flowId: 'pursue',
    fromStepId: 'verify-step',
    outcome: 'continue',
    to: 'review-step',
  },
  {
    kind: 'route',
    flowId: 'pursue',
    fromStepId: 'verify-step',
    outcome: 'retry',
    to: 'batch-step',
  },
  {
    kind: 'route',
    flowId: 'pursue',
    fromStepId: 'verify-step',
    outcome: 'stop',
    to: '@stop',
  },
  {
    kind: 'input-key',
    flowId: 'pursue',
    stepId: 'review-step',
    key: 'brief',
    schemaName: 'pursuit.contract@v1',
  },
  {
    kind: 'input-key',
    flowId: 'pursue',
    stepId: 'review-step',
    key: 'change',
    schemaName: 'pursuit.batch@v1',
  },
  {
    kind: 'input-key',
    flowId: 'pursue',
    stepId: 'review-step',
    key: 'verification',
    schemaName: 'pursuit.verification@v1',
  },
  {
    kind: 'step',
    flowId: 'pursue',
    stepId: 'review-step',
    title: 'Review - check pursuit coordination',
    stage: 'review',
    block: 'review',
    output: 'pursuit.review@v1',
    evidenceRequirements: ['verdict', 'findings', 'confidence', 'required fixes'],
    execution: {
      kind: 'relay',
      role: 'reviewer',
    },
    protocol: 'pursuit-review@v1',
    writes: {
      report_path: 'reports/pursuit/review.json',
      request_path: 'reports/relay/pursuit-review.request.json',
      receipt_path: 'reports/relay/pursuit-review.receipt.txt',
      result_path: 'reports/relay/pursuit-review.result.json',
    },
    check: {
      pass: ['clean', 'needs-followup'],
    },
    skillSlots: [],
  },
  {
    kind: 'route',
    flowId: 'pursue',
    fromStepId: 'review-step',
    outcome: 'continue',
    to: 'close-step',
  },
  {
    kind: 'route',
    flowId: 'pursue',
    fromStepId: 'review-step',
    outcome: 'retry',
    to: 'batch-step',
  },
  {
    kind: 'route',
    flowId: 'pursue',
    fromStepId: 'review-step',
    outcome: 'stop',
    to: '@stop',
  },
  {
    kind: 'input-key',
    flowId: 'pursue',
    stepId: 'close-step',
    key: 'brief',
    schemaName: 'pursuit.contract@v1',
  },
  {
    kind: 'input-key',
    flowId: 'pursue',
    stepId: 'close-step',
    key: 'graph',
    schemaName: 'pursuit.graph@v1',
  },
  {
    kind: 'input-key',
    flowId: 'pursue',
    stepId: 'close-step',
    key: 'plan',
    schemaName: 'pursuit.wave-plan@v1',
  },
  {
    kind: 'input-key',
    flowId: 'pursue',
    stepId: 'close-step',
    key: 'verification',
    schemaName: 'pursuit.verification@v1',
  },
  {
    kind: 'input-key',
    flowId: 'pursue',
    stepId: 'close-step',
    key: 'review',
    schemaName: 'pursuit.review@v1',
  },
  {
    kind: 'input-key',
    flowId: 'pursue',
    stepId: 'close-step',
    key: 'batch',
    schemaName: 'pursuit.batch@v1',
  },
  {
    kind: 'step',
    flowId: 'pursue',
    stepId: 'close-step',
    title: 'Close - summarize pursuit result',
    stage: 'close',
    block: 'close-with-evidence',
    output: 'pursuit.result@v1',
    evidenceRequirements: ['outcome', 'evidence pointers', 'residual risks', 'follow-ups'],
    execution: {
      kind: 'compose',
    },
    protocol: 'pursuit-close@v1',
    writes: {
      report_path: 'reports/pursuit-result.json',
    },
    check: {
      required: ['summary', 'outcome', 'evidence_links'],
    },
    skillSlots: [],
  },
  {
    kind: 'route',
    flowId: 'pursue',
    fromStepId: 'close-step',
    outcome: 'complete',
    to: '@complete',
  },
  {
    kind: 'route',
    flowId: 'pursue',
    fromStepId: 'close-step',
    outcome: 'stop',
    to: '@stop',
  },
  {
    kind: 'route',
    flowId: 'pursue',
    fromStepId: 'close-step',
    outcome: 'handoff',
    to: '@handoff',
  },
  {
    kind: 'route',
    flowId: 'pursue',
    fromStepId: 'close-step',
    outcome: 'escalate',
    to: '@escalate',
  },
  {
    kind: 'registered-report',
    flowId: 'pursue',
    schemaName: 'pursuit.batch@v1',
    channel: 'relay',
  },
  {
    kind: 'registered-report',
    flowId: 'pursue',
    schemaName: 'pursuit.review@v1',
    channel: 'relay',
  },
  {
    kind: 'registered-report',
    flowId: 'pursue',
    schemaName: 'pursuit.contract@v1',
    channel: 'report',
  },
  {
    kind: 'registered-report',
    flowId: 'pursue',
    schemaName: 'pursuit.graph@v1',
    channel: 'report',
  },
  {
    kind: 'registered-report',
    flowId: 'pursue',
    schemaName: 'pursuit.wave-plan@v1',
    channel: 'report',
  },
  {
    kind: 'registered-report',
    flowId: 'pursue',
    schemaName: 'pursuit.verification@v1',
    channel: 'report',
  },
  {
    kind: 'registered-report',
    flowId: 'pursue',
    schemaName: 'pursuit.result@v1',
    channel: 'report',
  },
  {
    kind: 'writer-binding',
    flowId: 'pursue',
    slot: 'compose',
    resultSchemaName: 'pursuit.contract@v1',
  },
  {
    kind: 'writer-binding',
    flowId: 'pursue',
    slot: 'compose',
    resultSchemaName: 'pursuit.graph@v1',
  },
  {
    kind: 'writer-binding',
    flowId: 'pursue',
    slot: 'compose',
    resultSchemaName: 'pursuit.wave-plan@v1',
  },
  {
    kind: 'writer-binding',
    flowId: 'pursue',
    slot: 'close',
    resultSchemaName: 'pursuit.result@v1',
  },
  {
    kind: 'writer-binding',
    flowId: 'pursue',
    slot: 'verification',
    resultSchemaName: 'pursuit.verification@v1',
  },
  {
    kind: 'progress',
    flowId: 'pursue',
    stepId: 'contract-step',
    taskTitle: 'Frame the work',
    activeText: 'Framing the work',
  },
  {
    kind: 'progress',
    flowId: 'pursue',
    stepId: 'graph-step',
    taskTitle: 'Coordinate the work',
    activeText: 'Coordinating the work',
  },
  {
    kind: 'progress',
    flowId: 'pursue',
    stepId: 'wave-plan-step',
    taskTitle: 'Plan the work',
    activeText: 'Planning the work',
  },
  {
    kind: 'progress',
    flowId: 'pursue',
    stepId: 'batch-step',
    taskTitle: 'Make the change',
    activeText: 'Making the change',
    relayRole: 'implementer',
  },
  {
    kind: 'progress',
    flowId: 'pursue',
    stepId: 'verify-step',
    taskTitle: 'Check the work',
    activeText: 'Checking the work',
  },
  {
    kind: 'progress',
    flowId: 'pursue',
    stepId: 'review-step',
    taskTitle: 'Check the result',
    activeText: 'Checking the result',
    relayRole: 'reviewer',
  },
  {
    kind: 'progress',
    flowId: 'pursue',
    stepId: 'close-step',
    taskTitle: 'Wrap up',
    activeText: 'Wrapping up',
  },
  {
    kind: 'primary-result',
    flowId: 'pursue',
    schemaName: 'pursuit.result@v1',
    path: 'reports/pursuit-result.json',
    label: 'Pursuit result',
  },
] as const satisfies readonly FlowFact[];
