/**
 * Catalog generator. Reads a Catalog and updates generated surfaces.
 * Block targets patch inline marker blocks. File targets write whole-file output.
 * Throws on missing or malformed markers (never silently skips).
 */

import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname } from "node:path";

import type { Catalog, GenerateResult, GenerateTarget } from "./types.js";

interface GenerateOptions {
  readFile?: (path: string) => string;
  writeFile?: (path: string, content: string) => void;
}

interface PendingWrite {
  content: string;
  filePath: string;
}

function readTargetContent(readFile: (path: string) => string, filePath: string): string {
  try {
    return readFile(filePath);
  } catch (error) {
    const code = (error as NodeJS.ErrnoException | undefined)?.code;
    if (code === "ENOENT") {
      return "";
    }

    throw error;
  }
}

export function collectPendingWrites(
  catalog: Catalog,
  targets: GenerateTarget[],
  opts?: Pick<GenerateOptions, "readFile">,
): PendingWrite[] {
  const readFile = opts?.readFile ?? ((path: string) => readFileSync(path, "utf-8"));
  const pendingWrites: PendingWrite[] = [];
  const stagedContents = new Map<string, string>();

  for (const target of targets) {
    const currentContent = stagedContents.has(target.filePath)
      ? stagedContents.get(target.filePath)!
      : readTargetContent(readFile, target.filePath);

    if ("blockName" in target) {
      const nextContent = patchBlock(
        currentContent,
        target.blockName,
        target.render(catalog),
        target.filePath,
      );

      if (nextContent !== currentContent) {
        stagedContents.set(target.filePath, nextContent);
        pendingWrites.push({ content: nextContent, filePath: target.filePath });
      }
      continue;
    }

    const nextContent = target.render(catalog);

    if (nextContent !== currentContent) {
      stagedContents.set(target.filePath, nextContent);
      pendingWrites.push({ content: nextContent, filePath: target.filePath });
    }
  }

  return pendingWrites;
}

export function generate(
  catalog: Catalog,
  targets: GenerateTarget[],
  opts?: GenerateOptions,
): GenerateResult {
  const writeFile = opts?.writeFile ?? ((path: string, content: string) => {
    writeFileSync(path, content, "utf-8");
  });
  const pendingWrites = collectPendingWrites(catalog, targets, opts);

  for (const pendingWrite of pendingWrites) {
    mkdirSync(dirname(pendingWrite.filePath), { recursive: true });
    writeFile(pendingWrite.filePath, pendingWrite.content);
  }

  return {
    patchedFiles: pendingWrites.map((pendingWrite) => pendingWrite.filePath),
  };
}

function patchBlock(
  content: string,
  blockName: string,
  rendered: string,
  filePath: string,
): string {
  const lines = content.split("\n");
  const beginMarker = `<!-- BEGIN ${blockName} -->`;
  const endMarker = `<!-- END ${blockName} -->`;

  const beginIdx = lines.findIndex((line) => line.trim() === beginMarker);
  if (beginIdx === -1) {
    throw new Error(`catalog-compiler: ${filePath} -- missing marker <!-- BEGIN ${blockName} -->`);
  }

  const endIdx = lines.findIndex((line, index) => index > beginIdx && line.trim() === endMarker);
  if (endIdx === -1) {
    throw new Error(
      `catalog-compiler: ${filePath} -- found <!-- BEGIN ${blockName} --> but missing <!-- END ${blockName} -->`,
    );
  }

  const doNotEdit = "<!-- DO NOT EDIT -- generated by catalog-compiler -->";
  const newBlock = [doNotEdit, rendered].join("\n");
  return [
    ...lines.slice(0, beginIdx + 1),
    newBlock,
    ...lines.slice(endIdx),
  ].join("\n");
}
