import { describe, it, expect } from "vitest";
import { generate } from "./generate.js";
import type { Catalog, GenerateTarget } from "./types.js";

const SAMPLE_CATALOG: Catalog = [
  {
    kind: "circuit",
    id: "cleanup",
    dir: "cleanup",
    version: "2026-04-01",
    purpose: "Systematic cleanup.",
    entryCommand: undefined,
    expertCommand: "/circuit:cleanup",
    entryModes: ["auto", "default"],
    skillName: "circuit:cleanup",
    skillDescription: "Systematic cleanup.",
  },
  {
    kind: "circuit",
    id: "run",
    dir: "run",
    version: "2026-04-03",
    purpose: "Adaptive supergraph circuit.",
    entryCommand: "/circuit",
    expertCommand: "/circuit:run",
    entryModes: ["adversarial", "default", "quick"],
    skillName: "circuit:run",
    skillDescription: "Adaptive supergraph circuit.",
  },
  {
    kind: "utility",
    id: "workers",
    dir: "workers",
    skillName: "workers",
    skillDescription: "Autonomous batch orchestrator.",
  },
];

function simpleRender(catalog: Catalog): string {
  return catalog.map((e) => `- ${e.id}`).join("\n");
}

function makeFs(files: Record<string, string>) {
  const store = { ...files };
  return {
    readFile: (p: string) => {
      if (!(p in store)) throw new Error(`ENOENT: ${p}`);
      return store[p];
    },
    writeFile: (p: string, c: string) => {
      store[p] = c;
    },
    store,
  };
}

describe("generate", () => {
  it("patches content between markers", () => {
    const fs = makeFs({
      "README.md": [
        "# Title",
        "<!-- BEGIN CIRCUIT_TABLE -->",
        "old content",
        "<!-- END CIRCUIT_TABLE -->",
        "footer",
      ].join("\n"),
    });

    const targets: GenerateTarget[] = [
      { filePath: "README.md", blockName: "CIRCUIT_TABLE", render: simpleRender },
    ];

    const result = generate(SAMPLE_CATALOG, targets, fs);
    expect(result.patchedFiles).toEqual(["README.md"]);

    const output = fs.store["README.md"];
    expect(output).toContain("<!-- BEGIN CIRCUIT_TABLE -->");
    expect(output).toContain("<!-- DO NOT EDIT -- generated by catalog-compiler -->");
    expect(output).toContain("- cleanup");
    expect(output).toContain("- run");
    expect(output).toContain("- workers");
    expect(output).toContain("<!-- END CIRCUIT_TABLE -->");
    expect(output).not.toContain("old content");
    expect(output).toContain("footer");
  });

  it("replaces existing DO NOT EDIT line on re-run", () => {
    const fs = makeFs({
      "README.md": [
        "<!-- BEGIN BLOCK -->",
        "<!-- DO NOT EDIT -- generated by catalog-compiler -->",
        "stale content",
        "<!-- END BLOCK -->",
      ].join("\n"),
    });

    const targets: GenerateTarget[] = [
      { filePath: "README.md", blockName: "BLOCK", render: () => "fresh" },
    ];

    generate(SAMPLE_CATALOG, targets, fs);
    const lines = fs.store["README.md"].split("\n");
    // Should have exactly one DO NOT EDIT line
    const doNotEditCount = lines.filter((l: string) =>
      l.includes("DO NOT EDIT"),
    ).length;
    expect(doNotEditCount).toBe(1);
    expect(fs.store["README.md"]).toContain("fresh");
    expect(fs.store["README.md"]).not.toContain("stale content");
  });

  it("throws on missing BEGIN marker", () => {
    const fs = makeFs({
      "README.md": "# Title\nno markers here\n",
    });

    const targets: GenerateTarget[] = [
      { filePath: "README.md", blockName: "CIRCUIT_TABLE", render: simpleRender },
    ];

    expect(() => generate(SAMPLE_CATALOG, targets, fs)).toThrow(
      "missing marker <!-- BEGIN CIRCUIT_TABLE -->",
    );
  });

  it("throws on orphaned BEGIN without END", () => {
    const fs = makeFs({
      "README.md": "# Title\n<!-- BEGIN CIRCUIT_TABLE -->\nstuff\n",
    });

    const targets: GenerateTarget[] = [
      { filePath: "README.md", blockName: "CIRCUIT_TABLE", render: simpleRender },
    ];

    expect(() => generate(SAMPLE_CATALOG, targets, fs)).toThrow(
      "found <!-- BEGIN CIRCUIT_TABLE --> but missing <!-- END CIRCUIT_TABLE -->",
    );
  });

  it("produces deterministic output for identical input", () => {
    const make = () =>
      makeFs({
        "README.md": [
          "<!-- BEGIN T -->",
          "old",
          "<!-- END T -->",
        ].join("\n"),
      });

    const targets: GenerateTarget[] = [
      { filePath: "README.md", blockName: "T", render: simpleRender },
    ];

    const fs1 = make();
    const fs2 = make();
    generate(SAMPLE_CATALOG, targets, fs1);
    generate(SAMPLE_CATALOG, targets, fs2);

    expect(fs1.store["README.md"]).toBe(fs2.store["README.md"]);
  });

  it("does not write file when content is unchanged", () => {
    // Generate once to get the expected output
    const fs1 = makeFs({
      "README.md": [
        "<!-- BEGIN T -->",
        "old",
        "<!-- END T -->",
      ].join("\n"),
    });
    const targets: GenerateTarget[] = [
      { filePath: "README.md", blockName: "T", render: simpleRender },
    ];
    generate(SAMPLE_CATALOG, targets, fs1);

    // Now run again with the already-patched content
    let writeCount = 0;
    const fs2 = {
      readFile: () => fs1.store["README.md"],
      writeFile: () => { writeCount++; },
    };
    const result = generate(SAMPLE_CATALOG, targets, fs2);
    expect(writeCount).toBe(0);
    expect(result.patchedFiles).toEqual([]);
  });

  it("handles multiple targets in one call", () => {
    const fs = makeFs({
      "a.md": "<!-- BEGIN X -->\nold\n<!-- END X -->",
      "b.md": "<!-- BEGIN Y -->\nold\n<!-- END Y -->",
    });

    const targets: GenerateTarget[] = [
      { filePath: "a.md", blockName: "X", render: () => "content-a" },
      { filePath: "b.md", blockName: "Y", render: () => "content-b" },
    ];

    const result = generate(SAMPLE_CATALOG, targets, fs);
    expect(result.patchedFiles).toHaveLength(2);
    expect(fs.store["a.md"]).toContain("content-a");
    expect(fs.store["b.md"]).toContain("content-b");
  });
});
