/**
 * Catalog generator. Reads a Catalog and patches inline marker blocks in target files.
 * Throws on missing or malformed markers (never silently skips).
 */

import type { Catalog, GenerateTarget, GenerateResult } from "./types.js";

interface GenerateOptions {
  readFile?: (path: string) => string;
  writeFile?: (path: string, content: string) => void;
}

export function generate(
  catalog: Catalog,
  targets: GenerateTarget[],
  opts?: GenerateOptions,
): GenerateResult {
  const readFile = opts?.readFile ?? ((p: string) => {
    const { readFileSync } = require("node:fs");
    return readFileSync(p, "utf-8");
  });
  const writeFile = opts?.writeFile ?? ((p: string, c: string) => {
    const { writeFileSync } = require("node:fs");
    writeFileSync(p, c, "utf-8");
  });

  const patchedFiles: string[] = [];

  for (const target of targets) {
    const content = readFile(target.filePath);
    const patched = patchBlock(content, target.blockName, target.render(catalog), target.filePath);

    if (patched !== content) {
      writeFile(target.filePath, patched);
      patchedFiles.push(target.filePath);
    }
  }

  return { patchedFiles };
}

function patchBlock(
  content: string,
  blockName: string,
  rendered: string,
  filePath: string,
): string {
  const lines = content.split("\n");
  const beginMarker = `<!-- BEGIN ${blockName} -->`;
  const endMarker = `<!-- END ${blockName} -->`;

  const beginIdx = lines.findIndex((l) => l.trim() === beginMarker);
  if (beginIdx === -1) {
    throw new Error(
      `catalog-compiler: ${filePath} — missing marker <!-- BEGIN ${blockName} -->`,
    );
  }

  const endIdx = lines.findIndex((l, i) => i > beginIdx && l.trim() === endMarker);
  if (endIdx === -1) {
    throw new Error(
      `catalog-compiler: ${filePath} — found <!-- BEGIN ${blockName} --> but missing <!-- END ${blockName} -->`,
    );
  }

  const doNotEdit = `<!-- DO NOT EDIT — generated by catalog-compiler -->`;
  const newBlock = [doNotEdit, rendered].join("\n");
  const newLines = [
    ...lines.slice(0, beginIdx + 1),
    newBlock,
    ...lines.slice(endIdx),
  ];

  return newLines.join("\n");
}
