import type { FlowFact } from '../flow-definition.js';

export const exploreFacts = [
  {
    kind: 'flow',
    flowId: 'explore',
    title: 'Explore Schematic',
    purpose:
      'Explore flow: frame the investigation, analyze the subject, either synthesize and critique findings or run a decision tournament, then close with findings plus evidence. All modes use Frame, Analyze, Plan or Decision, and Close; critique is embedded inside the Plan/Decision stage rather than exposed as a separate canonical Review stage.',
    status: 'active',
    version: '0.1.0',
    visibility: 'public',
    startsAt: 'frame-step',
    stagePathPolicy: {
      mode: 'partial',
      omits: ['act', 'verify', 'review'],
      rationale:
        'Explore is an investigation and decision flow. Synthesize, critique, and tournament stress review are all embedded inside the canonical Plan/Decision stage. Verify is omitted because Explore output is not executable and uses evidence/seam proof rather than mechanical command verification. See src/flows/explore/contract.md §Canonical stage set for the full rationale.',
    },
  },
  {
    kind: 'path',
    flowId: 'explore',
    pathKind: 'schematic',
    path: 'src/flows/explore/schematic.json',
  },
  {
    kind: 'path',
    flowId: 'explore',
    pathKind: 'command',
    path: 'src/flows/explore/command.md',
  },
  {
    kind: 'path',
    flowId: 'explore',
    pathKind: 'contract',
    path: 'src/flows/explore/contract.md',
  },
  {
    kind: 'entry',
    flowId: 'explore',
    include: ['explore', 'investigate', 'research', 'understand'],
    exclude: [],
    intentPrefixes: ['explore', 'investigate', 'decide'],
  },
  {
    kind: 'mode',
    flowId: 'explore',
    name: 'default',
    depth: 'standard',
    description: 'Default explore entry mode — seeds the run at Frame at standard depth.',
  },
  {
    kind: 'mode',
    flowId: 'explore',
    name: 'lite',
    depth: 'lite',
    description:
      'Lite Explore entry mode — frames, analyzes, and closes with a compact Plan/Decision pass.',
  },
  {
    kind: 'mode',
    flowId: 'explore',
    name: 'deep',
    depth: 'deep',
    description:
      'Deep Explore entry mode — frames, analyzes, and spends more effort on Plan/Decision evidence and seam proof.',
  },
  {
    kind: 'mode',
    flowId: 'explore',
    name: 'tournament',
    depth: 'tournament',
    description:
      'Decision tournament entry mode — frames and analyzes the question, fans out option cases, pauses for a bounded tradeoff choice, then closes with the selected decision.',
  },
  {
    kind: 'mode',
    flowId: 'explore',
    name: 'autonomous',
    depth: 'autonomous',
    description:
      'Autonomous Explore entry mode — carries ambiguity forward when no safe checkpoint answer is available.',
  },
  {
    kind: 'initial-contract',
    flowId: 'explore',
    schemaName: 'task.intake@v1',
  },
  {
    kind: 'initial-contract',
    flowId: 'explore',
    schemaName: 'route.decision@v1',
  },
  {
    kind: 'initial-contract',
    flowId: 'explore',
    schemaName: 'context.packet@v1',
  },
  {
    kind: 'contract-alias',
    flowId: 'explore',
    generic: 'flow.brief@v1',
    actual: 'explore.brief@v1',
  },
  {
    kind: 'contract-alias',
    flowId: 'explore',
    generic: 'diagnosis.result@v1',
    actual: 'explore.analysis@v1',
  },
  {
    kind: 'contract-alias',
    flowId: 'explore',
    generic: 'change.evidence@v1',
    actual: 'explore.compose@v1',
  },
  {
    kind: 'contract-alias',
    flowId: 'explore',
    generic: 'review.verdict@v1',
    actual: 'explore.review-verdict@v1',
  },
  {
    kind: 'contract-alias',
    flowId: 'explore',
    generic: 'plan.strategy@v1',
    actual: 'explore.decision-options@v1',
  },
  {
    kind: 'contract-alias',
    flowId: 'explore',
    generic: 'plan.strategy@v1',
    actual: 'explore.tournament-aggregate@v1',
  },
  {
    kind: 'contract-alias',
    flowId: 'explore',
    generic: 'plan.strategy@v1',
    actual: 'explore.tournament-review@v1',
  },
  {
    kind: 'contract-alias',
    flowId: 'explore',
    generic: 'plan.strategy@v1',
    actual: 'explore.decision@v1',
  },
  {
    kind: 'contract-alias',
    flowId: 'explore',
    generic: 'flow.question@v1',
    actual: 'explore.tournament-review@v1',
  },
  {
    kind: 'contract-alias',
    flowId: 'explore',
    generic: 'flow.evidence@v1',
    actual: 'explore.tournament-aggregate@v1',
  },
  {
    kind: 'contract-alias',
    flowId: 'explore',
    generic: 'decision.answer@v1',
    actual: 'explore.tradeoff-selection@v1',
  },
  {
    kind: 'contract-alias',
    flowId: 'explore',
    generic: 'flow.result@v1',
    actual: 'explore.result@v1',
  },
  {
    kind: 'stage',
    flowId: 'explore',
    stageId: 'frame-stage',
    canonical: 'frame',
    title: 'Frame',
  },
  {
    kind: 'stage',
    flowId: 'explore',
    stageId: 'analyze-stage',
    canonical: 'analyze',
    title: 'Analyze',
  },
  {
    kind: 'stage',
    flowId: 'explore',
    stageId: 'decision-stage',
    canonical: 'plan',
    title: 'Plan or Decision',
  },
  {
    kind: 'stage',
    flowId: 'explore',
    stageId: 'close-stage',
    canonical: 'close',
    title: 'Close',
  },
  {
    kind: 'input-key',
    flowId: 'explore',
    stepId: 'frame-step',
    key: 'task',
    schemaName: 'task.intake@v1',
  },
  {
    kind: 'input-key',
    flowId: 'explore',
    stepId: 'frame-step',
    key: 'route',
    schemaName: 'route.decision@v1',
  },
  {
    kind: 'step',
    flowId: 'explore',
    stepId: 'frame-step',
    title: 'Frame — produce explore.brief',
    stage: 'frame',
    block: 'frame',
    output: 'explore.brief@v1',
    evidenceRequirements: ['scope boundary', 'constraints', 'proof plan'],
    execution: {
      kind: 'compose',
    },
    protocol: 'explore-frame@v1',
    writes: {
      report_path: 'reports/brief.json',
    },
    check: {
      required: ['subject', 'success_condition'],
    },
    skillSlots: [],
  },
  {
    kind: 'route',
    flowId: 'explore',
    fromStepId: 'frame-step',
    outcome: 'continue',
    to: 'analyze-step',
  },
  {
    kind: 'route',
    flowId: 'explore',
    fromStepId: 'frame-step',
    outcome: 'stop',
    to: '@stop',
  },
  {
    kind: 'input-key',
    flowId: 'explore',
    stepId: 'analyze-step',
    key: 'brief',
    schemaName: 'explore.brief@v1',
  },
  {
    kind: 'input-key',
    flowId: 'explore',
    stepId: 'analyze-step',
    key: 'context',
    schemaName: 'context.packet@v1',
  },
  {
    kind: 'step',
    flowId: 'explore',
    stepId: 'analyze-step',
    title: 'Analyze — produce explore.analysis',
    stage: 'analyze',
    block: 'diagnose',
    output: 'explore.analysis@v1',
    evidenceRequirements: [
      'cause hypothesis',
      'confidence',
      'reproduction status',
      'diagnostic path',
    ],
    execution: {
      kind: 'compose',
    },
    protocol: 'explore-analyze@v1',
    writes: {
      report_path: 'reports/analysis.json',
    },
    check: {
      required: ['aspects'],
    },
    skillSlots: [],
  },
  {
    kind: 'route',
    flowId: 'explore',
    fromStepId: 'analyze-step',
    outcome: 'continue',
    to: 'synthesize-step',
    modeOverrides: {
      tournament: 'decision-options-step',
    },
  },
  {
    kind: 'route',
    flowId: 'explore',
    fromStepId: 'analyze-step',
    outcome: 'retry',
    to: 'analyze-step',
  },
  {
    kind: 'route',
    flowId: 'explore',
    fromStepId: 'analyze-step',
    outcome: 'stop',
    to: '@stop',
  },
  {
    kind: 'input-key',
    flowId: 'explore',
    stepId: 'synthesize-step',
    key: 'brief',
    schemaName: 'explore.brief@v1',
  },
  {
    kind: 'input-key',
    flowId: 'explore',
    stepId: 'synthesize-step',
    key: 'diagnosis',
    schemaName: 'explore.analysis@v1',
  },
  {
    kind: 'step',
    flowId: 'explore',
    stepId: 'synthesize-step',
    title: 'Synthesize — produce explore.compose (connector-bound relay)',
    stage: 'plan',
    block: 'plan',
    output: 'explore.compose@v1',
    evidenceRequirements: ['changed files', 'change rationale', 'declared follow-up proof'],
    execution: {
      kind: 'relay',
      role: 'implementer',
    },
    protocol: 'explore-synthesize@v1',
    writes: {
      report_path: 'reports/compose.json',
      request_path: 'reports/relay/synthesize.request.json',
      receipt_path: 'reports/relay/synthesize.receipt.txt',
      result_path: 'reports/relay/synthesize.result.json',
    },
    check: {
      pass: ['accept'],
    },
    skillSlots: [],
  },
  {
    kind: 'route',
    flowId: 'explore',
    fromStepId: 'synthesize-step',
    outcome: 'continue',
    to: 'review-step',
  },
  {
    kind: 'route',
    flowId: 'explore',
    fromStepId: 'synthesize-step',
    outcome: 'retry',
    to: 'synthesize-step',
  },
  {
    kind: 'route',
    flowId: 'explore',
    fromStepId: 'synthesize-step',
    outcome: 'stop',
    to: '@stop',
  },
  {
    kind: 'input-key',
    flowId: 'explore',
    stepId: 'review-step',
    key: 'brief',
    schemaName: 'explore.brief@v1',
  },
  {
    kind: 'input-key',
    flowId: 'explore',
    stepId: 'review-step',
    key: 'diagnosis',
    schemaName: 'explore.analysis@v1',
  },
  {
    kind: 'input-key',
    flowId: 'explore',
    stepId: 'review-step',
    key: 'change',
    schemaName: 'explore.compose@v1',
  },
  {
    kind: 'step',
    flowId: 'explore',
    stepId: 'review-step',
    title: 'Review — adversarial pass over compose (connector-bound relay)',
    stage: 'plan',
    block: 'review',
    output: 'explore.review-verdict@v1',
    evidenceRequirements: ['verdict', 'findings', 'confidence', 'required fixes'],
    execution: {
      kind: 'relay',
      role: 'reviewer',
    },
    protocol: 'explore-review@v1',
    writes: {
      report_path: 'reports/review-verdict.json',
      request_path: 'reports/relay/review.request.json',
      receipt_path: 'reports/relay/review.receipt.txt',
      result_path: 'reports/relay/review.result.json',
    },
    check: {
      pass: ['accept', 'accept-with-fold-ins'],
    },
    skillSlots: [],
  },
  {
    kind: 'route',
    flowId: 'explore',
    fromStepId: 'review-step',
    outcome: 'continue',
    to: 'close-step',
  },
  {
    kind: 'route',
    flowId: 'explore',
    fromStepId: 'review-step',
    outcome: 'retry',
    to: 'synthesize-step',
  },
  {
    kind: 'route',
    flowId: 'explore',
    fromStepId: 'review-step',
    outcome: 'revise',
    to: 'synthesize-step',
  },
  {
    kind: 'route',
    flowId: 'explore',
    fromStepId: 'review-step',
    outcome: 'stop',
    to: '@stop',
  },
  {
    kind: 'input-key',
    flowId: 'explore',
    stepId: 'decision-options-step',
    key: 'brief',
    schemaName: 'explore.brief@v1',
  },
  {
    kind: 'input-key',
    flowId: 'explore',
    stepId: 'decision-options-step',
    key: 'diagnosis',
    schemaName: 'explore.analysis@v1',
  },
  {
    kind: 'step',
    flowId: 'explore',
    stepId: 'decision-options-step',
    title: 'Decision — draft tournament options',
    stage: 'plan',
    block: 'plan',
    output: 'explore.decision-options@v1',
    evidenceRequirements: ['ordered steps', 'risk notes', 'proof strategy'],
    execution: {
      kind: 'compose',
    },
    protocol: 'explore-decision-options@v1',
    writes: {
      report_path: 'reports/decision-options.json',
    },
    check: {
      required: ['decision_question', 'options'],
    },
    skillSlots: [],
  },
  {
    kind: 'route',
    flowId: 'explore',
    fromStepId: 'decision-options-step',
    outcome: 'continue',
    to: 'proposal-fanout-step',
  },
  {
    kind: 'route',
    flowId: 'explore',
    fromStepId: 'decision-options-step',
    outcome: 'stop',
    to: '@stop',
  },
  {
    kind: 'input-key',
    flowId: 'explore',
    stepId: 'proposal-fanout-step',
    key: 'brief',
    schemaName: 'explore.brief@v1',
  },
  {
    kind: 'input-key',
    flowId: 'explore',
    stepId: 'proposal-fanout-step',
    key: 'options',
    schemaName: 'explore.decision-options@v1',
  },
  {
    kind: 'step',
    flowId: 'explore',
    stepId: 'proposal-fanout-step',
    title: 'Decision — fan out option cases',
    stage: 'plan',
    block: 'plan',
    output: 'explore.tournament-aggregate@v1',
    evidenceRequirements: ['ordered steps', 'risk notes', 'proof strategy'],
    execution: {
      kind: 'fanout',
    },
    protocol: 'explore-proposal-fanout@v1',
    writes: {
      report_path: 'reports/tournament-aggregate.json',
      branches_dir_path: 'reports/tournament-branches',
    },
    check: {
      pass: ['accept'],
    },
    skillSlots: [],
    fanout: {
      branches: {
        kind: 'dynamic',
        source_report: 'reports/decision-options.json',
        items_path: 'options',
        template: {
          branch_id: '$item.id',
          execution: {
            kind: 'relay',
            role: 'researcher',
            goal: '$item.best_case_prompt',
            report_schema: 'explore.tournament-proposal@v1',
            provenance_field: 'option_id',
          },
        },
        max_branches: 4,
      },
      concurrency: {
        kind: 'bounded',
        max: 2,
      },
      on_child_failure: 'abort-all',
      join: {
        policy: 'aggregate-only',
      },
    },
  },
  {
    kind: 'route',
    flowId: 'explore',
    fromStepId: 'proposal-fanout-step',
    outcome: 'continue',
    to: 'stress-proposals-step',
  },
  {
    kind: 'route',
    flowId: 'explore',
    fromStepId: 'proposal-fanout-step',
    outcome: 'stop',
    to: '@stop',
  },
  {
    kind: 'input-key',
    flowId: 'explore',
    stepId: 'stress-proposals-step',
    key: 'brief',
    schemaName: 'explore.brief@v1',
  },
  {
    kind: 'input-key',
    flowId: 'explore',
    stepId: 'stress-proposals-step',
    key: 'options',
    schemaName: 'explore.decision-options@v1',
  },
  {
    kind: 'input-key',
    flowId: 'explore',
    stepId: 'stress-proposals-step',
    key: 'aggregate',
    schemaName: 'explore.tournament-aggregate@v1',
  },
  {
    kind: 'step',
    flowId: 'explore',
    stepId: 'stress-proposals-step',
    title: 'Decision — stress proposals',
    stage: 'plan',
    block: 'plan',
    output: 'explore.tournament-review@v1',
    evidenceRequirements: ['ordered steps', 'risk notes', 'proof strategy'],
    execution: {
      kind: 'relay',
      role: 'reviewer',
    },
    protocol: 'explore-stress-proposals@v1',
    writes: {
      report_path: 'reports/tournament-review.json',
      request_path: 'reports/relay/tournament-review.request.json',
      receipt_path: 'reports/relay/tournament-review.receipt.txt',
      result_path: 'reports/relay/tournament-review.result.json',
    },
    check: {
      pass: ['recommend', 'no-clear-winner', 'needs-operator'],
    },
    skillSlots: [],
  },
  {
    kind: 'route',
    flowId: 'explore',
    fromStepId: 'stress-proposals-step',
    outcome: 'continue',
    to: 'tradeoff-checkpoint-step',
  },
  {
    kind: 'route',
    flowId: 'explore',
    fromStepId: 'stress-proposals-step',
    outcome: 'revise',
    to: 'decision-options-step',
  },
  {
    kind: 'route',
    flowId: 'explore',
    fromStepId: 'stress-proposals-step',
    outcome: 'stop',
    to: '@stop',
  },
  {
    kind: 'input-key',
    flowId: 'explore',
    stepId: 'tradeoff-checkpoint-step',
    key: 'question',
    schemaName: 'explore.tournament-review@v1',
  },
  {
    kind: 'input-key',
    flowId: 'explore',
    stepId: 'tradeoff-checkpoint-step',
    key: 'evidence',
    schemaName: 'explore.tournament-aggregate@v1',
  },
  {
    kind: 'step',
    flowId: 'explore',
    stepId: 'tradeoff-checkpoint-step',
    title: 'Decision — tradeoff checkpoint',
    stage: 'plan',
    block: 'human-decision',
    output: 'explore.tradeoff-selection@v1',
    evidenceRequirements: ['question', 'available options', 'selected option', 'answer source'],
    execution: {
      kind: 'checkpoint',
    },
    protocol: 'explore-tradeoff-checkpoint@v1',
    writes: {
      checkpoint_request_path: 'reports/checkpoints/tradeoff-request.json',
      checkpoint_response_path: 'reports/checkpoints/tradeoff-response.json',
    },
    check: {
      allow: ['option-1', 'option-2', 'option-3', 'option-4'],
    },
    skillSlots: [],
    checkpointPolicy: {
      prompt:
        'Choose the option Circuit should close with. This checkpoint only supports final option choices; ask-for-more-evidence and stop routes are intentionally not encoded until the runtime has executable route semantics for them.',
      choices: [
        {
          id: 'option-1',
          label: 'Option 1',
          description: 'Close with the first drafted option.',
        },
        {
          id: 'option-2',
          label: 'Option 2',
          description: 'Close with the second drafted option.',
        },
        {
          id: 'option-3',
          label: 'Option 3',
          description: 'Close with the third drafted option.',
        },
        {
          id: 'option-4',
          label: 'Option 4',
          description: 'Close with the fourth drafted option.',
        },
      ],
      safe_default_choice: 'option-1',
    },
  },
  {
    kind: 'route',
    flowId: 'explore',
    fromStepId: 'tradeoff-checkpoint-step',
    outcome: 'continue',
    to: 'decision-step',
  },
  {
    kind: 'route',
    flowId: 'explore',
    fromStepId: 'tradeoff-checkpoint-step',
    outcome: 'stop',
    to: '@stop',
  },
  {
    kind: 'input-key',
    flowId: 'explore',
    stepId: 'decision-step',
    key: 'brief',
    schemaName: 'explore.brief@v1',
  },
  {
    kind: 'input-key',
    flowId: 'explore',
    stepId: 'decision-step',
    key: 'options',
    schemaName: 'explore.decision-options@v1',
  },
  {
    kind: 'input-key',
    flowId: 'explore',
    stepId: 'decision-step',
    key: 'aggregate',
    schemaName: 'explore.tournament-aggregate@v1',
  },
  {
    kind: 'input-key',
    flowId: 'explore',
    stepId: 'decision-step',
    key: 'review',
    schemaName: 'explore.tournament-review@v1',
  },
  {
    kind: 'step',
    flowId: 'explore',
    stepId: 'decision-step',
    title: 'Decision — compose final choice',
    stage: 'plan',
    block: 'plan',
    output: 'explore.decision@v1',
    evidenceRequirements: ['ordered steps', 'risk notes', 'proof strategy'],
    execution: {
      kind: 'compose',
    },
    protocol: 'explore-decision@v1',
    writes: {
      report_path: 'reports/decision.json',
    },
    check: {
      required: ['decision', 'selected_option_id', 'rationale'],
    },
    skillSlots: [],
  },
  {
    kind: 'route',
    flowId: 'explore',
    fromStepId: 'decision-step',
    outcome: 'continue',
    to: 'close-tournament-step',
  },
  {
    kind: 'route',
    flowId: 'explore',
    fromStepId: 'decision-step',
    outcome: 'stop',
    to: '@stop',
  },
  {
    kind: 'input-key',
    flowId: 'explore',
    stepId: 'close-tournament-step',
    key: 'brief',
    schemaName: 'explore.brief@v1',
  },
  {
    kind: 'input-key',
    flowId: 'explore',
    stepId: 'close-tournament-step',
    key: 'options',
    schemaName: 'explore.decision-options@v1',
  },
  {
    kind: 'input-key',
    flowId: 'explore',
    stepId: 'close-tournament-step',
    key: 'aggregate',
    schemaName: 'explore.tournament-aggregate@v1',
  },
  {
    kind: 'input-key',
    flowId: 'explore',
    stepId: 'close-tournament-step',
    key: 'review',
    schemaName: 'explore.tournament-review@v1',
  },
  {
    kind: 'input-key',
    flowId: 'explore',
    stepId: 'close-tournament-step',
    key: 'decision',
    schemaName: 'explore.decision@v1',
  },
  {
    kind: 'step',
    flowId: 'explore',
    stepId: 'close-tournament-step',
    title: 'Close — emit tournament result file',
    stage: 'close',
    block: 'close-with-evidence',
    output: 'explore.result@v1',
    evidenceRequirements: ['outcome', 'evidence pointers', 'residual risks', 'follow-ups'],
    execution: {
      kind: 'compose',
    },
    protocol: 'explore-close-tournament@v1',
    writes: {
      report_path: 'reports/explore-result.json',
    },
    check: {
      required: ['summary', 'verdict_snapshot'],
    },
    skillSlots: [],
  },
  {
    kind: 'route',
    flowId: 'explore',
    fromStepId: 'close-tournament-step',
    outcome: 'complete',
    to: '@complete',
  },
  {
    kind: 'route',
    flowId: 'explore',
    fromStepId: 'close-tournament-step',
    outcome: 'stop',
    to: '@stop',
  },
  {
    kind: 'input-key',
    flowId: 'explore',
    stepId: 'close-step',
    key: 'brief',
    schemaName: 'explore.brief@v1',
  },
  {
    kind: 'input-key',
    flowId: 'explore',
    stepId: 'close-step',
    key: 'compose',
    schemaName: 'explore.compose@v1',
  },
  {
    kind: 'input-key',
    flowId: 'explore',
    stepId: 'close-step',
    key: 'review',
    schemaName: 'explore.review-verdict@v1',
  },
  {
    kind: 'step',
    flowId: 'explore',
    stepId: 'close-step',
    title: 'Close — emit final result file',
    stage: 'close',
    block: 'close-with-evidence',
    output: 'explore.result@v1',
    evidenceRequirements: ['outcome', 'evidence pointers', 'residual risks', 'follow-ups'],
    execution: {
      kind: 'compose',
    },
    protocol: 'explore-close@v1',
    writes: {
      report_path: 'reports/explore-result.json',
    },
    check: {
      required: ['summary', 'verdict_snapshot'],
    },
    skillSlots: [],
  },
  {
    kind: 'route',
    flowId: 'explore',
    fromStepId: 'close-step',
    outcome: 'complete',
    to: '@complete',
  },
  {
    kind: 'route',
    flowId: 'explore',
    fromStepId: 'close-step',
    outcome: 'stop',
    to: '@stop',
  },
  {
    kind: 'registered-report',
    flowId: 'explore',
    schemaName: 'explore.compose@v1',
    channel: 'relay',
  },
  {
    kind: 'registered-report',
    flowId: 'explore',
    schemaName: 'explore.review-verdict@v1',
    channel: 'relay',
  },
  {
    kind: 'registered-report',
    flowId: 'explore',
    schemaName: 'explore.tournament-proposal@v1',
    channel: 'relay',
  },
  {
    kind: 'registered-report',
    flowId: 'explore',
    schemaName: 'explore.tournament-review@v1',
    channel: 'relay',
  },
  {
    kind: 'registered-report',
    flowId: 'explore',
    schemaName: 'explore.brief@v1',
    channel: 'report',
  },
  {
    kind: 'registered-report',
    flowId: 'explore',
    schemaName: 'explore.analysis@v1',
    channel: 'report',
  },
  {
    kind: 'registered-report',
    flowId: 'explore',
    schemaName: 'explore.decision-options@v1',
    channel: 'report',
  },
  {
    kind: 'registered-report',
    flowId: 'explore',
    schemaName: 'explore.tournament-aggregate@v1',
    channel: 'report',
  },
  {
    kind: 'registered-report',
    flowId: 'explore',
    schemaName: 'explore.decision@v1',
    channel: 'report',
  },
  {
    kind: 'registered-report',
    flowId: 'explore',
    schemaName: 'explore.result@v1',
    channel: 'report',
  },
  {
    kind: 'writer-binding',
    flowId: 'explore',
    slot: 'compose',
    resultSchemaName: 'explore.brief@v1',
  },
  {
    kind: 'writer-binding',
    flowId: 'explore',
    slot: 'compose',
    resultSchemaName: 'explore.analysis@v1',
  },
  {
    kind: 'writer-binding',
    flowId: 'explore',
    slot: 'compose',
    resultSchemaName: 'explore.decision-options@v1',
  },
  {
    kind: 'writer-binding',
    flowId: 'explore',
    slot: 'compose',
    resultSchemaName: 'explore.decision@v1',
  },
  {
    kind: 'writer-binding',
    flowId: 'explore',
    slot: 'close',
    resultSchemaName: 'explore.result@v1',
  },
  {
    kind: 'progress',
    flowId: 'explore',
    stepId: 'frame-step',
    taskTitle: 'Frame the work',
    activeText: 'Framing the work',
  },
  {
    kind: 'progress',
    flowId: 'explore',
    stepId: 'analyze-step',
    taskTitle: 'Check the context',
    activeText: 'Checking the context',
  },
  {
    kind: 'progress',
    flowId: 'explore',
    stepId: 'synthesize-step',
    taskTitle: 'Draft the recommendation',
    activeText: 'Drafting the recommendation',
    relayRole: 'implementer',
  },
  {
    kind: 'progress',
    flowId: 'explore',
    stepId: 'review-step',
    taskTitle: 'Check the recommendation',
    activeText: 'Checking the recommendation',
    relayRole: 'reviewer',
  },
  {
    kind: 'progress',
    flowId: 'explore',
    stepId: 'decision-options-step',
    taskTitle: 'Draft the options',
    activeText: 'Drafting the options',
  },
  {
    kind: 'progress',
    flowId: 'explore',
    stepId: 'proposal-fanout-step',
    taskTitle: 'Compare the options',
    activeText: 'Comparing the options',
  },
  {
    kind: 'progress',
    flowId: 'explore',
    stepId: 'stress-proposals-step',
    taskTitle: 'Check the options',
    activeText: 'Checking the options',
    relayRole: 'reviewer',
  },
  {
    kind: 'progress',
    flowId: 'explore',
    stepId: 'tradeoff-checkpoint-step',
    taskTitle: 'Compare the options',
    activeText: 'Comparing the options',
  },
  {
    kind: 'progress',
    flowId: 'explore',
    stepId: 'decision-step',
    taskTitle: 'Draft the recommendation',
    activeText: 'Drafting the recommendation',
  },
  {
    kind: 'progress',
    flowId: 'explore',
    stepId: 'close-tournament-step',
    taskTitle: 'Wrap up',
    activeText: 'Wrapping up',
  },
  {
    kind: 'progress',
    flowId: 'explore',
    stepId: 'close-step',
    taskTitle: 'Wrap up',
    activeText: 'Wrapping up',
  },
  {
    kind: 'primary-result',
    flowId: 'explore',
    schemaName: 'explore.result@v1',
    path: 'reports/explore-result.json',
    label: 'Explore result',
  },
] as const satisfies readonly FlowFact[];
