import type { FlowFact } from '../flow-definition.js';

export const fixFacts = [
  {
    kind: 'flow',
    flowId: 'fix',
    title: 'Fix Schematic',
    purpose:
      'Fix flow: capture problem boundary, prove the pre-fix regression before any specialist relay can edit the checkout, gather context, diagnose, apply a focused change, verify, review (in standard depth), and close with evidence. If the standard reviewer connector is unavailable after proof passes, Fix closes with the proof artifacts and marks review skipped. Lite mode skips the review relay and closes immediately after verification via the fix-verify route_overrides.continue.lite override. fix-no-repro-decision and fix-handoff remain in the schematic as authoring intent for future ask/handoff routing in the runtime; they are unreachable at compile and do not appear in the emitted compiled flows.',
    status: 'active',
    version: '0.1.0',
    visibility: 'public',
    startsAt: 'fix-frame',
    stagePathPolicy: {
      mode: 'partial',
      omits: ['plan'],
      rationale:
        "Fix follows Frame, Analyze, Act, Verify, Review, Close. The Plan stage is omitted because Fix's planning is folded into Diagnose during the Analyze stage — there is no separate plan-of-attack report distinct from the diagnosis.",
    },
  },
  {
    kind: 'path',
    flowId: 'fix',
    pathKind: 'schematic',
    path: 'src/flows/fix/schematic.json',
  },
  {
    kind: 'path',
    flowId: 'fix',
    pathKind: 'command',
    path: 'src/flows/fix/command.md',
  },
  {
    kind: 'path',
    flowId: 'fix',
    pathKind: 'contract',
    path: 'src/flows/fix/contract.md',
  },
  {
    kind: 'entry',
    flowId: 'fix',
    include: ['fix', 'bug', 'broken', 'regression', 'incident', 'outage', 'diagnose'],
    exclude: [],
    intentPrefixes: ['fix', 'diagnose'],
  },
  {
    kind: 'mode',
    flowId: 'fix',
    name: 'default',
    depth: 'standard',
    description: 'Default Fix entry mode — standard depth with full review pass.',
  },
  {
    kind: 'mode',
    flowId: 'fix',
    name: 'lite',
    depth: 'lite',
    description:
      'Lite Fix entry mode — skips the review relay and closes immediately after verification.',
  },
  {
    kind: 'mode',
    flowId: 'fix',
    name: 'deep',
    depth: 'deep',
    description:
      'Deep Fix entry mode — standard graph at deep depth (more thorough analysis and review).',
  },
  {
    kind: 'mode',
    flowId: 'fix',
    name: 'autonomous',
    depth: 'autonomous',
    description:
      'Autonomous Fix entry mode — standard graph at autonomous depth; safe-default checkpoint choices apply.',
  },
  {
    kind: 'initial-contract',
    flowId: 'fix',
    schemaName: 'task.intake@v1',
  },
  {
    kind: 'initial-contract',
    flowId: 'fix',
    schemaName: 'route.decision@v1',
  },
  {
    kind: 'initial-contract',
    flowId: 'fix',
    schemaName: 'context.request@v1',
  },
  {
    kind: 'initial-contract',
    flowId: 'fix',
    schemaName: 'flow.question@v1',
  },
  {
    kind: 'initial-contract',
    flowId: 'fix',
    schemaName: 'verification.plan@v1',
  },
  {
    kind: 'initial-contract',
    flowId: 'fix',
    schemaName: 'flow.state@v1',
  },
  {
    kind: 'contract-alias',
    flowId: 'fix',
    generic: 'flow.brief@v1',
    actual: 'fix.brief@v1',
  },
  {
    kind: 'contract-alias',
    flowId: 'fix',
    generic: 'context.packet@v1',
    actual: 'fix.context@v1',
  },
  {
    kind: 'contract-alias',
    flowId: 'fix',
    generic: 'diagnosis.result@v1',
    actual: 'fix.diagnosis@v1',
  },
  {
    kind: 'contract-alias',
    flowId: 'fix',
    generic: 'decision.answer@v1',
    actual: 'fix.no-repro-decision@v1',
  },
  {
    kind: 'contract-alias',
    flowId: 'fix',
    generic: 'flow.evidence@v1',
    actual: 'fix.diagnosis@v1',
  },
  {
    kind: 'contract-alias',
    flowId: 'fix',
    generic: 'change.evidence@v1',
    actual: 'fix.change@v1',
  },
  {
    kind: 'contract-alias',
    flowId: 'fix',
    generic: 'verification.result@v1',
    actual: 'fix.verification@v1',
  },
  {
    kind: 'contract-alias',
    flowId: 'fix',
    generic: 'verification.result@v1',
    actual: 'fix.regression-proof@v1',
  },
  {
    kind: 'contract-alias',
    flowId: 'fix',
    generic: 'verification.result@v1',
    actual: 'fix.baseline-snapshot@v1',
  },
  {
    kind: 'contract-alias',
    flowId: 'fix',
    generic: 'verification.result@v1',
    actual: 'fix.regression-rerun@v1',
  },
  {
    kind: 'contract-alias',
    flowId: 'fix',
    generic: 'verification.result@v1',
    actual: 'fix.change-set@v1',
  },
  {
    kind: 'contract-alias',
    flowId: 'fix',
    generic: 'review.verdict@v1',
    actual: 'fix.review@v1',
  },
  {
    kind: 'contract-alias',
    flowId: 'fix',
    generic: 'flow.result@v1',
    actual: 'fix.result@v1',
  },
  {
    kind: 'stage',
    flowId: 'fix',
    stageId: 'frame-stage',
    canonical: 'frame',
    title: 'Frame',
  },
  {
    kind: 'stage',
    flowId: 'fix',
    stageId: 'analyze-stage',
    canonical: 'analyze',
    title: 'Analyze',
  },
  {
    kind: 'stage',
    flowId: 'fix',
    stageId: 'act-stage',
    canonical: 'act',
    title: 'Act',
  },
  {
    kind: 'stage',
    flowId: 'fix',
    stageId: 'verify-stage',
    canonical: 'verify',
    title: 'Verify',
  },
  {
    kind: 'stage',
    flowId: 'fix',
    stageId: 'review-stage',
    canonical: 'review',
    title: 'Review',
  },
  {
    kind: 'stage',
    flowId: 'fix',
    stageId: 'close-stage',
    canonical: 'close',
    title: 'Close',
  },
  {
    kind: 'input-key',
    flowId: 'fix',
    stepId: 'fix-frame',
    key: 'task',
    schemaName: 'task.intake@v1',
  },
  {
    kind: 'input-key',
    flowId: 'fix',
    stepId: 'fix-frame',
    key: 'route',
    schemaName: 'route.decision@v1',
  },
  {
    kind: 'step',
    flowId: 'fix',
    stepId: 'fix-frame',
    title: 'Frame — confirm Fix brief',
    stage: 'frame',
    block: 'frame',
    output: 'fix.brief@v1',
    evidenceRequirements: ['scope boundary', 'constraints', 'proof plan'],
    execution: {
      kind: 'compose',
    },
    protocol: 'fix-frame@v1',
    writes: {
      report_path: 'reports/fix/brief.json',
    },
    check: {
      required: ['problem_statement', 'scope', 'regression_contract', 'success_criteria'],
    },
    skillSlots: [],
  },
  {
    kind: 'route',
    flowId: 'fix',
    fromStepId: 'fix-frame',
    outcome: 'continue',
    to: 'fix-regression-baseline',
  },
  {
    kind: 'route',
    flowId: 'fix',
    fromStepId: 'fix-frame',
    outcome: 'revise',
    to: 'fix-frame',
  },
  {
    kind: 'route',
    flowId: 'fix',
    fromStepId: 'fix-frame',
    outcome: 'ask',
    to: '@stop',
  },
  {
    kind: 'route',
    flowId: 'fix',
    fromStepId: 'fix-frame',
    outcome: 'stop',
    to: '@stop',
  },
  {
    kind: 'input-key',
    flowId: 'fix',
    stepId: 'fix-gather-context',
    key: 'brief',
    schemaName: 'fix.brief@v1',
  },
  {
    kind: 'input-key',
    flowId: 'fix',
    stepId: 'fix-gather-context',
    key: 'request',
    schemaName: 'context.request@v1',
  },
  {
    kind: 'step',
    flowId: 'fix',
    stepId: 'fix-gather-context',
    title: 'Analyze — gather problem context',
    stage: 'analyze',
    block: 'gather-context',
    output: 'fix.context@v1',
    evidenceRequirements: ['source list', 'observations', 'confidence notes'],
    execution: {
      kind: 'relay',
      role: 'researcher',
    },
    protocol: 'fix-gather-context@v1',
    writes: {
      report_path: 'reports/fix/context.json',
      request_path: 'reports/relay/fix-gather-context.request.json',
      receipt_path: 'reports/relay/fix-gather-context.receipt.txt',
      result_path: 'reports/relay/fix-gather-context.result.json',
    },
    check: {
      pass: ['accept'],
    },
    skillSlots: [],
  },
  {
    kind: 'route',
    flowId: 'fix',
    fromStepId: 'fix-gather-context',
    outcome: 'continue',
    to: 'fix-diagnose',
  },
  {
    kind: 'route',
    flowId: 'fix',
    fromStepId: 'fix-gather-context',
    outcome: 'retry',
    to: 'fix-gather-context',
  },
  {
    kind: 'route',
    flowId: 'fix',
    fromStepId: 'fix-gather-context',
    outcome: 'ask',
    to: '@stop',
  },
  {
    kind: 'route',
    flowId: 'fix',
    fromStepId: 'fix-gather-context',
    outcome: 'stop',
    to: '@stop',
  },
  {
    kind: 'input-key',
    flowId: 'fix',
    stepId: 'fix-diagnose',
    key: 'brief',
    schemaName: 'fix.brief@v1',
  },
  {
    kind: 'input-key',
    flowId: 'fix',
    stepId: 'fix-diagnose',
    key: 'context',
    schemaName: 'fix.context@v1',
  },
  {
    kind: 'step',
    flowId: 'fix',
    stepId: 'fix-diagnose',
    title: 'Analyze — diagnose problem',
    stage: 'analyze',
    block: 'diagnose',
    output: 'fix.diagnosis@v1',
    evidenceRequirements: [
      'cause hypothesis',
      'confidence',
      'reproduction status',
      'diagnostic path',
    ],
    execution: {
      kind: 'relay',
      role: 'researcher',
    },
    protocol: 'fix-diagnose@v1',
    writes: {
      report_path: 'reports/fix/diagnosis.json',
      request_path: 'reports/relay/fix-diagnose.request.json',
      receipt_path: 'reports/relay/fix-diagnose.receipt.txt',
      result_path: 'reports/relay/fix-diagnose.result.json',
    },
    check: {
      pass: ['accept'],
    },
    skillSlots: [],
  },
  {
    kind: 'route',
    flowId: 'fix',
    fromStepId: 'fix-diagnose',
    outcome: 'continue',
    to: 'fix-act',
  },
  {
    kind: 'route',
    flowId: 'fix',
    fromStepId: 'fix-diagnose',
    outcome: 'retry',
    to: 'fix-gather-context',
  },
  {
    kind: 'route',
    flowId: 'fix',
    fromStepId: 'fix-diagnose',
    outcome: 'ask',
    to: 'fix-no-repro-decision',
  },
  {
    kind: 'route',
    flowId: 'fix',
    fromStepId: 'fix-diagnose',
    outcome: 'stop',
    to: '@stop',
  },
  {
    kind: 'input-key',
    flowId: 'fix',
    stepId: 'fix-no-repro-decision',
    key: 'question',
    schemaName: 'flow.question@v1',
  },
  {
    kind: 'input-key',
    flowId: 'fix',
    stepId: 'fix-no-repro-decision',
    key: 'evidence',
    schemaName: 'fix.diagnosis@v1',
  },
  {
    kind: 'step',
    flowId: 'fix',
    stepId: 'fix-no-repro-decision',
    title: 'Analyze — choose path forward when reproduction is uncertain',
    stage: 'analyze',
    block: 'human-decision',
    output: 'fix.no-repro-decision@v1',
    evidenceRequirements: ['question', 'available options', 'selected option', 'answer source'],
    execution: {
      kind: 'checkpoint',
    },
    protocol: 'fix-no-repro-decision@v1',
    writes: {
      checkpoint_request_path: 'reports/checkpoints/fix-no-repro-decision-request.json',
      checkpoint_response_path: 'reports/checkpoints/fix-no-repro-decision-response.json',
    },
    check: {
      allow: ['continue'],
    },
    skillSlots: [],
    checkpointPolicy: {
      prompt: 'Diagnosis did not cleanly reproduce the bug. Choose how to proceed.',
      choices: [
        {
          id: 'continue',
          label: 'Continue with a focused fix anyway',
        },
      ],
      safe_default_choice: 'continue',
      safe_autonomous_choice: 'continue',
    },
  },
  {
    kind: 'route',
    flowId: 'fix',
    fromStepId: 'fix-no-repro-decision',
    outcome: 'continue',
    to: 'fix-act',
  },
  {
    kind: 'route',
    flowId: 'fix',
    fromStepId: 'fix-no-repro-decision',
    outcome: 'revise',
    to: 'fix-diagnose',
  },
  {
    kind: 'route',
    flowId: 'fix',
    fromStepId: 'fix-no-repro-decision',
    outcome: 'stop',
    to: '@stop',
  },
  {
    kind: 'route',
    flowId: 'fix',
    fromStepId: 'fix-no-repro-decision',
    outcome: 'handoff',
    to: 'fix-handoff',
  },
  {
    kind: 'route',
    flowId: 'fix',
    fromStepId: 'fix-no-repro-decision',
    outcome: 'escalate',
    to: '@escalate',
  },
  {
    kind: 'input-key',
    flowId: 'fix',
    stepId: 'fix-regression-baseline',
    key: 'proof',
    schemaName: 'verification.plan@v1',
  },
  {
    kind: 'input-key',
    flowId: 'fix',
    stepId: 'fix-regression-baseline',
    key: 'brief',
    schemaName: 'fix.brief@v1',
  },
  {
    kind: 'step',
    flowId: 'fix',
    stepId: 'fix-regression-baseline',
    title: 'Verify — capture regression baseline',
    stage: 'verify',
    block: 'run-verification',
    output: 'fix.regression-proof@v1',
    evidenceRequirements: ['command list', 'exit status', 'bounded output', 'pass or fail'],
    execution: {
      kind: 'verification',
    },
    protocol: 'fix-regression-baseline@v1',
    writes: {
      report_path: 'reports/fix/regression-proof.json',
    },
    check: {
      required: ['status', 'overall_status'],
    },
    skillSlots: [],
  },
  {
    kind: 'route',
    flowId: 'fix',
    fromStepId: 'fix-regression-baseline',
    outcome: 'continue',
    to: 'fix-baseline-snapshot',
  },
  {
    kind: 'route',
    flowId: 'fix',
    fromStepId: 'fix-regression-baseline',
    outcome: 'retry',
    to: 'fix-frame',
  },
  {
    kind: 'route',
    flowId: 'fix',
    fromStepId: 'fix-regression-baseline',
    outcome: 'stop',
    to: '@stop',
  },
  {
    kind: 'input-key',
    flowId: 'fix',
    stepId: 'fix-baseline-snapshot',
    key: 'proof',
    schemaName: 'verification.plan@v1',
  },
  {
    kind: 'step',
    flowId: 'fix',
    stepId: 'fix-baseline-snapshot',
    title: 'Verify — snapshot pre-fix git state',
    stage: 'verify',
    block: 'run-verification',
    output: 'fix.baseline-snapshot@v1',
    evidenceRequirements: ['command list', 'exit status', 'bounded output', 'pass or fail'],
    execution: {
      kind: 'verification',
    },
    protocol: 'fix-baseline-snapshot@v1',
    writes: {
      report_path: 'reports/fix/baseline-snapshot.json',
    },
    check: {
      required: ['overall_status', 'head_sha'],
    },
    skillSlots: [],
  },
  {
    kind: 'route',
    flowId: 'fix',
    fromStepId: 'fix-baseline-snapshot',
    outcome: 'continue',
    to: 'fix-gather-context',
  },
  {
    kind: 'route',
    flowId: 'fix',
    fromStepId: 'fix-baseline-snapshot',
    outcome: 'stop',
    to: '@stop',
  },
  {
    kind: 'input-key',
    flowId: 'fix',
    stepId: 'fix-act',
    key: 'brief',
    schemaName: 'fix.brief@v1',
  },
  {
    kind: 'input-key',
    flowId: 'fix',
    stepId: 'fix-act',
    key: 'diagnosis',
    schemaName: 'fix.diagnosis@v1',
  },
  {
    kind: 'step',
    flowId: 'fix',
    stepId: 'fix-act',
    title: 'Act — apply focused fix',
    stage: 'act',
    block: 'act',
    output: 'fix.change@v1',
    evidenceRequirements: ['changed files', 'change rationale', 'declared follow-up proof'],
    execution: {
      kind: 'relay',
      role: 'implementer',
    },
    protocol: 'fix-act@v1',
    writes: {
      report_path: 'reports/fix/change.json',
      request_path: 'reports/relay/fix-act.request.json',
      receipt_path: 'reports/relay/fix-act.receipt.txt',
      result_path: 'reports/relay/fix-act.result.json',
    },
    check: {
      pass: ['accept'],
    },
    skillSlots: [],
  },
  {
    kind: 'route',
    flowId: 'fix',
    fromStepId: 'fix-act',
    outcome: 'continue',
    to: 'fix-verify',
  },
  {
    kind: 'route',
    flowId: 'fix',
    fromStepId: 'fix-act',
    outcome: 'retry',
    to: 'fix-act',
  },
  {
    kind: 'route',
    flowId: 'fix',
    fromStepId: 'fix-act',
    outcome: 'ask',
    to: 'fix-no-repro-decision',
  },
  {
    kind: 'route',
    flowId: 'fix',
    fromStepId: 'fix-act',
    outcome: 'stop',
    to: '@stop',
  },
  {
    kind: 'route',
    flowId: 'fix',
    fromStepId: 'fix-act',
    outcome: 'handoff',
    to: 'fix-handoff',
  },
  {
    kind: 'input-key',
    flowId: 'fix',
    stepId: 'fix-verify',
    key: 'proof',
    schemaName: 'verification.plan@v1',
  },
  {
    kind: 'input-key',
    flowId: 'fix',
    stepId: 'fix-verify',
    key: 'brief',
    schemaName: 'fix.brief@v1',
  },
  {
    kind: 'input-key',
    flowId: 'fix',
    stepId: 'fix-verify',
    key: 'change',
    schemaName: 'fix.change@v1',
  },
  {
    kind: 'step',
    flowId: 'fix',
    stepId: 'fix-verify',
    title: 'Verify — run Fix proof',
    stage: 'verify',
    block: 'run-verification',
    output: 'fix.verification@v1',
    evidenceRequirements: ['command list', 'exit status', 'bounded output', 'pass or fail'],
    execution: {
      kind: 'verification',
    },
    protocol: 'fix-verify@v1',
    writes: {
      report_path: 'reports/fix/verification.json',
    },
    check: {
      required: ['overall_status', 'commands'],
    },
    skillSlots: [],
  },
  {
    kind: 'route',
    flowId: 'fix',
    fromStepId: 'fix-verify',
    outcome: 'continue',
    to: 'fix-change-set',
  },
  {
    kind: 'route',
    flowId: 'fix',
    fromStepId: 'fix-verify',
    outcome: 'retry',
    to: 'fix-act',
  },
  {
    kind: 'route',
    flowId: 'fix',
    fromStepId: 'fix-verify',
    outcome: 'ask',
    to: 'fix-no-repro-decision',
  },
  {
    kind: 'route',
    flowId: 'fix',
    fromStepId: 'fix-verify',
    outcome: 'stop',
    to: '@stop',
  },
  {
    kind: 'input-key',
    flowId: 'fix',
    stepId: 'fix-change-set',
    key: 'proof',
    schemaName: 'verification.plan@v1',
  },
  {
    kind: 'input-key',
    flowId: 'fix',
    stepId: 'fix-change-set',
    key: 'baseline',
    schemaName: 'fix.baseline-snapshot@v1',
  },
  {
    kind: 'input-key',
    flowId: 'fix',
    stepId: 'fix-change-set',
    key: 'change',
    schemaName: 'fix.change@v1',
  },
  {
    kind: 'step',
    flowId: 'fix',
    stepId: 'fix-change-set',
    title: 'Verify — compute fix change-set',
    stage: 'verify',
    block: 'run-verification',
    output: 'fix.change-set@v1',
    evidenceRequirements: ['command list', 'exit status', 'bounded output', 'pass or fail'],
    execution: {
      kind: 'verification',
    },
    protocol: 'fix-change-set@v1',
    writes: {
      report_path: 'reports/fix/change-set.json',
    },
    check: {
      required: ['status', 'overall_status'],
    },
    skillSlots: [],
  },
  {
    kind: 'route',
    flowId: 'fix',
    fromStepId: 'fix-change-set',
    outcome: 'continue',
    to: 'fix-regression-rerun',
  },
  {
    kind: 'route',
    flowId: 'fix',
    fromStepId: 'fix-change-set',
    outcome: 'retry',
    to: 'fix-act',
  },
  {
    kind: 'route',
    flowId: 'fix',
    fromStepId: 'fix-change-set',
    outcome: 'stop',
    to: '@stop',
  },
  {
    kind: 'input-key',
    flowId: 'fix',
    stepId: 'fix-regression-rerun',
    key: 'proof',
    schemaName: 'verification.plan@v1',
  },
  {
    kind: 'input-key',
    flowId: 'fix',
    stepId: 'fix-regression-rerun',
    key: 'brief',
    schemaName: 'fix.brief@v1',
  },
  {
    kind: 'step',
    flowId: 'fix',
    stepId: 'fix-regression-rerun',
    title: 'Verify — rerun regression command after fix',
    stage: 'verify',
    block: 'run-verification',
    output: 'fix.regression-rerun@v1',
    evidenceRequirements: ['command list', 'exit status', 'bounded output', 'pass or fail'],
    execution: {
      kind: 'verification',
    },
    protocol: 'fix-regression-rerun@v1',
    writes: {
      report_path: 'reports/fix/regression-rerun.json',
    },
    check: {
      required: ['status', 'overall_status'],
    },
    skillSlots: [],
  },
  {
    kind: 'route',
    flowId: 'fix',
    fromStepId: 'fix-regression-rerun',
    outcome: 'continue',
    to: 'fix-review',
    modeOverrides: {
      lite: 'fix-close-lite',
    },
  },
  {
    kind: 'route',
    flowId: 'fix',
    fromStepId: 'fix-regression-rerun',
    outcome: 'retry',
    to: 'fix-act',
  },
  {
    kind: 'route',
    flowId: 'fix',
    fromStepId: 'fix-regression-rerun',
    outcome: 'stop',
    to: '@stop',
  },
  {
    kind: 'input-key',
    flowId: 'fix',
    stepId: 'fix-review',
    key: 'brief',
    schemaName: 'fix.brief@v1',
  },
  {
    kind: 'input-key',
    flowId: 'fix',
    stepId: 'fix-review',
    key: 'change',
    schemaName: 'fix.change@v1',
  },
  {
    kind: 'input-key',
    flowId: 'fix',
    stepId: 'fix-review',
    key: 'verification',
    schemaName: 'fix.verification@v1',
  },
  {
    kind: 'step',
    flowId: 'fix',
    stepId: 'fix-review',
    title: 'Review — independent audit of Fix change',
    stage: 'review',
    block: 'review',
    output: 'fix.review@v1',
    evidenceRequirements: ['verdict', 'findings', 'confidence', 'required fixes'],
    execution: {
      kind: 'relay',
      role: 'reviewer',
    },
    protocol: 'fix-review@v1',
    writes: {
      report_path: 'reports/fix/review.json',
      request_path: 'reports/relay/fix-review.request.json',
      receipt_path: 'reports/relay/fix-review.receipt.txt',
      result_path: 'reports/relay/fix-review.result.json',
    },
    check: {
      pass: ['accept', 'accept-with-fixes'],
    },
    skillSlots: [],
  },
  {
    kind: 'route',
    flowId: 'fix',
    fromStepId: 'fix-review',
    outcome: 'continue',
    to: 'fix-close',
  },
  {
    kind: 'route',
    flowId: 'fix',
    fromStepId: 'fix-review',
    outcome: 'connector-failed',
    to: 'fix-close',
  },
  {
    kind: 'route',
    flowId: 'fix',
    fromStepId: 'fix-review',
    outcome: 'retry',
    to: 'fix-act',
  },
  {
    kind: 'route',
    flowId: 'fix',
    fromStepId: 'fix-review',
    outcome: 'revise',
    to: 'fix-act',
  },
  {
    kind: 'route',
    flowId: 'fix',
    fromStepId: 'fix-review',
    outcome: 'ask',
    to: 'fix-no-repro-decision',
  },
  {
    kind: 'route',
    flowId: 'fix',
    fromStepId: 'fix-review',
    outcome: 'stop',
    to: '@stop',
  },
  {
    kind: 'input-key',
    flowId: 'fix',
    stepId: 'fix-close-lite',
    key: 'brief',
    schemaName: 'fix.brief@v1',
  },
  {
    kind: 'input-key',
    flowId: 'fix',
    stepId: 'fix-close-lite',
    key: 'context',
    schemaName: 'fix.context@v1',
  },
  {
    kind: 'input-key',
    flowId: 'fix',
    stepId: 'fix-close-lite',
    key: 'diagnosis',
    schemaName: 'fix.diagnosis@v1',
  },
  {
    kind: 'input-key',
    flowId: 'fix',
    stepId: 'fix-close-lite',
    key: 'regression',
    schemaName: 'fix.regression-proof@v1',
  },
  {
    kind: 'input-key',
    flowId: 'fix',
    stepId: 'fix-close-lite',
    key: 'baseline_snapshot',
    schemaName: 'fix.baseline-snapshot@v1',
  },
  {
    kind: 'input-key',
    flowId: 'fix',
    stepId: 'fix-close-lite',
    key: 'change',
    schemaName: 'fix.change@v1',
  },
  {
    kind: 'input-key',
    flowId: 'fix',
    stepId: 'fix-close-lite',
    key: 'verification',
    schemaName: 'fix.verification@v1',
  },
  {
    kind: 'input-key',
    flowId: 'fix',
    stepId: 'fix-close-lite',
    key: 'regression_rerun',
    schemaName: 'fix.regression-rerun@v1',
  },
  {
    kind: 'input-key',
    flowId: 'fix',
    stepId: 'fix-close-lite',
    key: 'change_set',
    schemaName: 'fix.change-set@v1',
  },
  {
    kind: 'step',
    flowId: 'fix',
    stepId: 'fix-close-lite',
    title: 'Close (lite) — emit Fix result without review',
    stage: 'close',
    block: 'close-with-evidence',
    output: 'fix.result@v1',
    evidenceRequirements: ['outcome', 'evidence pointers', 'residual risks', 'follow-ups'],
    execution: {
      kind: 'compose',
    },
    protocol: 'fix-close-lite@v1',
    writes: {
      report_path: 'reports/fix-result.json',
    },
    check: {
      required: [
        'summary',
        'outcome',
        'verification_status',
        'regression_status',
        'change_set_status',
        'review_status',
        'evidence_links',
      ],
    },
    skillSlots: [],
  },
  {
    kind: 'route',
    flowId: 'fix',
    fromStepId: 'fix-close-lite',
    outcome: 'complete',
    to: '@complete',
  },
  {
    kind: 'route',
    flowId: 'fix',
    fromStepId: 'fix-close-lite',
    outcome: 'stop',
    to: '@stop',
  },
  {
    kind: 'route',
    flowId: 'fix',
    fromStepId: 'fix-close-lite',
    outcome: 'handoff',
    to: 'fix-handoff',
  },
  {
    kind: 'route',
    flowId: 'fix',
    fromStepId: 'fix-close-lite',
    outcome: 'escalate',
    to: '@escalate',
  },
  {
    kind: 'input-key',
    flowId: 'fix',
    stepId: 'fix-close',
    key: 'brief',
    schemaName: 'fix.brief@v1',
  },
  {
    kind: 'input-key',
    flowId: 'fix',
    stepId: 'fix-close',
    key: 'context',
    schemaName: 'fix.context@v1',
  },
  {
    kind: 'input-key',
    flowId: 'fix',
    stepId: 'fix-close',
    key: 'diagnosis',
    schemaName: 'fix.diagnosis@v1',
  },
  {
    kind: 'input-key',
    flowId: 'fix',
    stepId: 'fix-close',
    key: 'regression',
    schemaName: 'fix.regression-proof@v1',
  },
  {
    kind: 'input-key',
    flowId: 'fix',
    stepId: 'fix-close',
    key: 'baseline_snapshot',
    schemaName: 'fix.baseline-snapshot@v1',
  },
  {
    kind: 'input-key',
    flowId: 'fix',
    stepId: 'fix-close',
    key: 'change',
    schemaName: 'fix.change@v1',
  },
  {
    kind: 'input-key',
    flowId: 'fix',
    stepId: 'fix-close',
    key: 'verification',
    schemaName: 'fix.verification@v1',
  },
  {
    kind: 'input-key',
    flowId: 'fix',
    stepId: 'fix-close',
    key: 'regression_rerun',
    schemaName: 'fix.regression-rerun@v1',
  },
  {
    kind: 'input-key',
    flowId: 'fix',
    stepId: 'fix-close',
    key: 'change_set',
    schemaName: 'fix.change-set@v1',
  },
  {
    kind: 'input-key',
    flowId: 'fix',
    stepId: 'fix-close',
    key: 'review',
    schemaName: 'fix.review@v1',
  },
  {
    kind: 'step',
    flowId: 'fix',
    stepId: 'fix-close',
    title: 'Close — emit Fix result',
    stage: 'close',
    block: 'close-with-evidence',
    output: 'fix.result@v1',
    evidenceRequirements: ['outcome', 'evidence pointers', 'residual risks', 'follow-ups'],
    execution: {
      kind: 'compose',
    },
    protocol: 'fix-close@v1',
    writes: {
      report_path: 'reports/fix-result.json',
    },
    check: {
      required: [
        'summary',
        'outcome',
        'verification_status',
        'regression_status',
        'change_set_status',
        'review_status',
        'evidence_links',
      ],
    },
    skillSlots: [],
  },
  {
    kind: 'route',
    flowId: 'fix',
    fromStepId: 'fix-close',
    outcome: 'complete',
    to: '@complete',
  },
  {
    kind: 'route',
    flowId: 'fix',
    fromStepId: 'fix-close',
    outcome: 'stop',
    to: '@stop',
  },
  {
    kind: 'route',
    flowId: 'fix',
    fromStepId: 'fix-close',
    outcome: 'handoff',
    to: 'fix-handoff',
  },
  {
    kind: 'route',
    flowId: 'fix',
    fromStepId: 'fix-close',
    outcome: 'escalate',
    to: '@escalate',
  },
  {
    kind: 'input-key',
    flowId: 'fix',
    stepId: 'fix-handoff',
    key: 'state',
    schemaName: 'flow.state@v1',
  },
  {
    kind: 'input-key',
    flowId: 'fix',
    stepId: 'fix-handoff',
    key: 'brief',
    schemaName: 'fix.brief@v1',
  },
  {
    kind: 'step',
    flowId: 'fix',
    stepId: 'fix-handoff',
    title: 'Persist Fix handoff',
    stage: 'close',
    block: 'handoff',
    output: 'continuity.record@v1',
    evidenceRequirements: [
      'goal',
      'completed moves',
      'pending evidence',
      'next action',
      'known debt',
    ],
    execution: {
      kind: 'compose',
    },
    protocol: 'fix-handoff@v1',
    writes: {
      report_path: 'reports/fix/handoff.json',
    },
    check: {
      required: ['goal', 'next_action'],
    },
    skillSlots: [],
  },
  {
    kind: 'route',
    flowId: 'fix',
    fromStepId: 'fix-handoff',
    outcome: 'complete',
    to: '@handoff',
  },
  {
    kind: 'route',
    flowId: 'fix',
    fromStepId: 'fix-handoff',
    outcome: 'stop',
    to: '@stop',
  },
  {
    kind: 'registered-report',
    flowId: 'fix',
    schemaName: 'fix.context@v1',
    channel: 'relay',
  },
  {
    kind: 'registered-report',
    flowId: 'fix',
    schemaName: 'fix.diagnosis@v1',
    channel: 'relay',
  },
  {
    kind: 'registered-report',
    flowId: 'fix',
    schemaName: 'fix.change@v1',
    channel: 'relay',
  },
  {
    kind: 'registered-report',
    flowId: 'fix',
    schemaName: 'fix.review@v1',
    channel: 'relay',
  },
  {
    kind: 'registered-report',
    flowId: 'fix',
    schemaName: 'fix.brief@v1',
    channel: 'report',
  },
  {
    kind: 'registered-report',
    flowId: 'fix',
    schemaName: 'fix.no-repro-decision@v1',
    channel: 'report',
  },
  {
    kind: 'registered-report',
    flowId: 'fix',
    schemaName: 'fix.regression-proof@v1',
    channel: 'report',
  },
  {
    kind: 'registered-report',
    flowId: 'fix',
    schemaName: 'fix.baseline-snapshot@v1',
    channel: 'report',
  },
  {
    kind: 'registered-report',
    flowId: 'fix',
    schemaName: 'fix.verification@v1',
    channel: 'report',
  },
  {
    kind: 'registered-report',
    flowId: 'fix',
    schemaName: 'fix.regression-rerun@v1',
    channel: 'report',
  },
  {
    kind: 'registered-report',
    flowId: 'fix',
    schemaName: 'fix.change-set@v1',
    channel: 'report',
  },
  {
    kind: 'registered-report',
    flowId: 'fix',
    schemaName: 'fix.result@v1',
    channel: 'report',
  },
  {
    kind: 'writer-binding',
    flowId: 'fix',
    slot: 'compose',
    resultSchemaName: 'fix.brief@v1',
  },
  {
    kind: 'writer-binding',
    flowId: 'fix',
    slot: 'close',
    resultSchemaName: 'fix.result@v1',
  },
  {
    kind: 'writer-binding',
    flowId: 'fix',
    slot: 'verification',
    resultSchemaName: 'fix.regression-proof@v1',
  },
  {
    kind: 'writer-binding',
    flowId: 'fix',
    slot: 'verification',
    resultSchemaName: 'fix.baseline-snapshot@v1',
  },
  {
    kind: 'writer-binding',
    flowId: 'fix',
    slot: 'verification',
    resultSchemaName: 'fix.verification@v1',
  },
  {
    kind: 'writer-binding',
    flowId: 'fix',
    slot: 'verification',
    resultSchemaName: 'fix.regression-rerun@v1',
  },
  {
    kind: 'writer-binding',
    flowId: 'fix',
    slot: 'verification',
    resultSchemaName: 'fix.change-set@v1',
  },
  {
    kind: 'progress',
    flowId: 'fix',
    stepId: 'fix-frame',
    taskTitle: 'Frame the work',
    activeText: 'Framing the work',
  },
  {
    kind: 'progress',
    flowId: 'fix',
    stepId: 'fix-gather-context',
    taskTitle: 'Check the context',
    activeText: 'Checking the context',
    relayRole: 'implementer',
  },
  {
    kind: 'progress',
    flowId: 'fix',
    stepId: 'fix-diagnose',
    taskTitle: 'Check the context',
    activeText: 'Checking the context',
    relayRole: 'implementer',
  },
  {
    kind: 'progress',
    flowId: 'fix',
    stepId: 'fix-no-repro-decision',
    taskTitle: 'Check the context',
    activeText: 'Checking the context',
  },
  {
    kind: 'progress',
    flowId: 'fix',
    stepId: 'fix-regression-baseline',
    taskTitle: 'Check the work',
    activeText: 'Checking the work',
  },
  {
    kind: 'progress',
    flowId: 'fix',
    stepId: 'fix-baseline-snapshot',
    taskTitle: 'Check the work',
    activeText: 'Checking the work',
  },
  {
    kind: 'progress',
    flowId: 'fix',
    stepId: 'fix-act',
    taskTitle: 'Make the change',
    activeText: 'Making the change',
    relayRole: 'implementer',
  },
  {
    kind: 'progress',
    flowId: 'fix',
    stepId: 'fix-verify',
    taskTitle: 'Check the work',
    activeText: 'Checking the work',
  },
  {
    kind: 'progress',
    flowId: 'fix',
    stepId: 'fix-change-set',
    taskTitle: 'Check the work',
    activeText: 'Checking the work',
  },
  {
    kind: 'progress',
    flowId: 'fix',
    stepId: 'fix-regression-rerun',
    taskTitle: 'Check the work',
    activeText: 'Checking the work',
  },
  {
    kind: 'progress',
    flowId: 'fix',
    stepId: 'fix-review',
    taskTitle: 'Check the result',
    activeText: 'Checking the result',
    relayRole: 'reviewer',
  },
  {
    kind: 'progress',
    flowId: 'fix',
    stepId: 'fix-close-lite',
    taskTitle: 'Wrap up',
    activeText: 'Wrapping up',
  },
  {
    kind: 'progress',
    flowId: 'fix',
    stepId: 'fix-close',
    taskTitle: 'Wrap up',
    activeText: 'Wrapping up',
  },
  {
    kind: 'progress',
    flowId: 'fix',
    stepId: 'fix-handoff',
    taskTitle: 'Wrap up',
    activeText: 'Wrapping up',
  },
  {
    kind: 'primary-result',
    flowId: 'fix',
    schemaName: 'fix.result@v1',
    path: 'reports/fix-result.json',
    label: 'Fix result',
  },
] as const satisfies readonly FlowFact[];
